<a href="https://colab.research.google.com/github/jiyoungemma/User-Log-data-analytics/blob/main/recommend_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 라이브러리 & 데이터 불러오기

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import matplotlib.pyplot as plt
import matplotlib.dates as dates
from datetime import datetime
%matplotlib inline
import pandas as pd
import datetime
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors

In [29]:
RFM_without_view = pd.read_csv("/content/drive/MyDrive/RFM_without_view.csv")

In [30]:
RFM_without_view.drop(columns=['field1', 'event_time','user_id.1','category_id', 'Recency','Monetary','Recency_score', 'Frequency_score', 'Monetary_score',
       'RFM_seg', 'RFM_score'], inplace=True)

In [5]:
RFM_without_view.head()

,event_type,category_code,brand,price,user_id,user_session,main_category,subcategory,Frequency
0,purchase,electronics.smartphone,samsung,130.76,543272936,8187d148-3c41-46d4-b0c0-9c08cd9dc564,electronics,smartphone,33
1,purchase,electronics.smartphone,apple,642.69,551377651,3c80f0d6-e9ec-4181-8c5c-837a30be2d68,electronics,smartphone,9
2,purchase,NaN,xiaomi,29.51,514591159,0e5dfc4b-2a55-43e6-8c05-97e1f07fbb56,NaN,NaN,1
3,purchase,furniture.bathroom.toilet,santeri,54.42,555332717,1dea3ee2-2ded-42e8-8e7a-4e2ad6ae942f,furniture,toilet,4
4,purchase,electronics.audio.headphone,apple,189.91,524601178,2af9b570-0942-4dcd-8f25-4d84fba82553,electronics,headphone,1

In [77]:
RFM_without_view.loc[RFM_without_view['Frequency'] == 1]

,event_type,product_id,category_code,brand,price,user_id,user_session,main_category,subcategory,Frequency,RFM_label
2,purchase,5100816,NaN,xiaomi,29.51,514591159,0e5dfc4b-2a55-43e6-8c05-97e1f07fbb56,NaN,NaN,1,segment5
4,purchase,4804055,electronics.audio.headphone,apple,189.91,524601178,2af9b570-0942-4dcd-8f25-4d84fba82553,electronics,headphone,1,segment5
8,purchase,6200687,appliances.environment.air_heater,oasis,28.03,548691404,b67cdbcb-b073-4271-b365-803c6fce53b0,appliances,air_heater,1,segment5
12,cart,1004833,electronics.smartphone,samsung,174.76,536415846,685b5b42-f597-4a69-ab4c-ef96a30bc454,electronics,smartphone,1,segment5
20,purchase,4804295,electronics.audio.headphone,xiaomi,23.13,540557704,0c990471-9407-4292-a6df-0cbc2f722a40,electronics,headphone,1,segment5
...,...,...,...,...,...,...,...,...,...,...,...
1382811,cart,5100816,NaN,xiaomi,29.58,514905226,6f25d2de-bb1c-4e68-b848-f03372fb6e7d,NaN,NaN,1,segment4
1382814,cart,1004250,electronics.smartphone,apple,787.50,514503441,d2169b3a-422b-4887-9149-ddf35e68e537,electronics,smartphone,1,segment2
1382816,purchase,1004250,electronics.smartphone,apple,787.50,514503441,d2169b3a-422b-4887-9149-ddf35e68e537,electronics,smartphone,1,segment2
1382818,purchase,5100816,NaN,xiaomi,29.58,514905226,6f25d2de-bb1c-4e68-b848-f03372fb6e7d,NaN,NaN,1,segment4
1382820,purchase,1002524,electronics.smartphone,apple,531.26,516662286,d1b46fb7-cf95-4b40-9460-f7abde16c4d3,electronics,smartphone,1,segment3

In [78]:
RFM_without_view.shape

(1382831, 11)

In [80]:
(530997 / 1382831) * 100

38.39926932502959

### computers dateframe

In [5]:
com_once = RFM_without_view.loc[(RFM_without_view['Frequency'] < 2) & (RFM_without_view['event_type'] == 'purchase') & (RFM_without_view['main_category'] == 'computers')]

In [6]:
com_once_user = RFM_without_view.loc[(RFM_without_view['Frequency'] < 2) & (RFM_without_view['event_type'] == 'purchase') & (RFM_without_view['main_category'] == 'computers')]

In [7]:
com_once.shape

(9353, 9)

In [8]:
com_once.columns

Index(['event_type', 'category_code', 'brand', 'price', 'user_id',
       'user_session', 'main_category', 'subcategory', 'Frequency'],
      dtype='object')

In [9]:
com_once_user.head()

,event_type,category_code,brand,price,user_id,user_session,main_category,subcategory,Frequency
38,purchase,computers.peripherals.printer,epson,116.73,513489079,63de1120-9d48-45d0-b024-500d1b95d71f,computers,printer,1
68,purchase,computers.components.hdd,kingston,66.67,523117953,629a0485-36c9-4a80-9f02-4a96382c3059,computers,hdd,1
167,purchase,computers.notebook,acer,532.81,549790258,56272bb8-9f35-4412-9f15-624c8ecda0f1,computers,notebook,1
412,purchase,computers.notebook,hp,285.51,555467053,8d2582ff-8031-4b06-819b-a653eb1cb832,computers,notebook,1
433,purchase,computers.notebook,hp,285.51,521162064,5622db13-66d1-4167-8bfa-b4f184aed29a,computers,notebook,1

In [7]:
com_once.drop(columns = ['event_type', 'user_session', 'main_category', 'Frequency'], inplace=True)
com_once = com_once.reset_index(drop=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [8]:
com_once_user.drop(columns = ['event_type', 'main_category', 'subcategory','Frequency'], inplace=True)
com_once_user = com_once_user.reset_index(drop=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [12]:
com_once

                      category_code     brand   price    user_id subcategory
0     computers.peripherals.printer     epson  116.73  513489079     printer
1          computers.components.hdd  kingston   66.67  523117953         hdd
2                computers.notebook      acer  532.81  549790258    notebook
3                computers.notebook        hp  285.51  555467053    notebook
4                computers.notebook        hp  285.51  521162064    notebook
...                             ...       ...     ...        ...         ...
9348             computers.notebook    lenovo  365.26  518406442    notebook
9349              computers.desktop        hp  720.48  566258164     desktop
9350    computers.peripherals.mouse    x-game    5.03  566267483       mouse
9351             computers.notebook      asus  352.96  513741972    notebook
9352             computers.notebook    lenovo  257.15  546977150    notebook

[9353 rows x 5 columns]

In [13]:
com_once_user.head()

,category_code,brand,price,user_id,user_session
0,computers.peripherals.printer,epson,116.73,513489079,63de1120-9d48-45d0-b024-500d1b95d71f
1,computers.components.hdd,kingston,66.67,523117953,629a0485-36c9-4a80-9f02-4a96382c3059
2,computers.notebook,acer,532.81,549790258,56272bb8-9f35-4412-9f15-624c8ecda0f1
3,computers.notebook,hp,285.51,555467053,8d2582ff-8031-4b06-819b-a653eb1cb832
4,computers.notebook,hp,285.51,521162064,5622db13-66d1-4167-8bfa-b4f184aed29a

In [14]:
com_once_user.isna().sum()

category_code      0
brand            228
price              0
user_id            0
user_session       0
dtype: int64

In [15]:
com_once.isna().sum()

category_code      0
brand            228
price              0
user_id            0
subcategory        0
dtype: int64

In [9]:
com_once_user.dropna(inplace=True)

In [10]:
com_once.dropna(inplace=True)

### computers 제품간 추천

In [11]:
tfidf = TfidfVectorizer()

# Fit 후 dtm을 만듭니다.(문서, 단어마다 tf-idf 값을 계산합니다)
dtm_tfidf = tfidf.fit_transform(com_once['category_code'])

In [153]:
dtm_tfidf_df= pd.DataFrame(dtm_tfidf.todense(), columns=tfidf.get_feature_names_out())
dtm_tfidf_df

,camera,components,computers,cooler,cpu,desktop,ebooks,hdd,keyboard,memory,monitor,motherboard,mouse,notebook,peripherals,power_supply,printer,videocards
0,0.0,0.00000,0.237006,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.613976,0.0,0.752903,0.0
1,0.0,0.59821,0.184131,0.0,0.0,0.000000,0.0,0.779898,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
2,0.0,0.00000,0.534484,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.845179,0.000000,0.0,0.000000,0.0
3,0.0,0.00000,0.534484,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.845179,0.000000,0.0,0.000000,0.0
4,0.0,0.00000,0.534484,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.845179,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9120,0.0,0.00000,0.534484,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.845179,0.000000,0.0,0.000000,0.0
9121,0.0,0.00000,0.301918,0.0,0.0,0.953334,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
9122,0.0,0.00000,0.191205,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.847403,0.000000,0.495327,0.0,0.000000,0.0
9123,0.0,0.00000,0.534484,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.845179,0.000000,0.0,0.000000,0.0
9124,0.0,0.00000,0.534484,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.845179,0.000000,0.0,0.000000,0.0

In [12]:
cosine_matrix = cosine_similarity(dtm_tfidf, dtm_tfidf)

In [13]:
np.round(cosine_matrix, 4)

array([[1.    , 0.0436, 0.1267, ..., 0.3494, 0.1267, 0.1267],
       [0.0436, 1.    , 0.0984, ..., 0.0352, 0.0984, 0.0984],
       [0.1267, 0.0984, 1.    , ..., 0.1022, 1.    , 1.    ],
       ...,
       [0.3494, 0.0352, 0.1022, ..., 1.    , 0.1022, 0.1022],
       [0.1267, 0.0984, 1.    , ..., 0.1022, 1.    , 1.    ],
       [0.1267, 0.0984, 1.    , ..., 0.1022, 1.    , 1.    ]])

In [22]:
category = {}
for i, c in enumerate(com_once['user_id']): 
  category[i] = c

category_id = {}
for i, c in category.items():
  category_id[c] = i

In [23]:
category_id

{513489079: 0,
 523117953: 1,
 549790258: 2,
 555467053: 3,
 521162064: 4,
 555468492: 5,
 538858285: 6,
 530820988: 7,
 533828408: 8,
 521819296: 9,
 512742880: 11,
 513250707: 12,
 512604234: 13,
 513861839: 14,
 531542244: 15,
 550000136: 16,
 550982997: 17,
 515567849: 18,
 515856194: 19,
 546884787: 20,
 546202787: 21,
 555485978: 22,
 554837844: 23,
 555485235: 24,
 520552458: 25,
 515104074: 26,
 517460166: 27,
 528769567: 28,
 517465372: 29,
 514531448: 30,
 526799174: 31,
 517529110: 32,
 536387441: 33,
 512374444: 34,
 514953614: 35,
 555495717: 36,
 555491795: 37,
 530123083: 38,
 539257365: 39,
 530233653: 40,
 544411220: 41,
 536838713: 42,
 555498267: 43,
 525197121: 44,
 553088582: 45,
 517010638: 46,
 512953546: 47,
 527790692: 48,
 551008846: 49,
 541539898: 50,
 516205307: 51,
 518105307: 52,
 512644482: 53,
 523099429: 54,
 541270844: 55,
 554633294: 57,
 555513645: 58,
 543745179: 59,
 522366714: 60,
 515582362: 61,
 544325552: 62,
 553629184: 63,
 522003699: 65,
 546358009: 66,
 531895455: 67,
 516204501: 68,
 555521765: 69,
 513014567: 70,
 519058549: 71,
 520176362: 73,
 555524716: 74,
 519637033: 75,
 536121390: 76,
 525082453: 77,
 515150344: 78,
 537306605: 79,
 514287655: 80,
 551137341: 81,
 512643994: 82,
 533746693: 83,
 518667476: 84,
 555537922: 85,
 516237176: 86,
 538739224: 87,
 548407232: 88,
 554623441: 89,
 554468738: 90,
 512524945: 91,
 550318201: 92,
 514570840: 93,
 518746424: 94,
 544121891: 95,
 555545407: 96,
 513068869: 99,
 513388925: 100,
 551708033: 101,
 526702292: 102,
 502469352: 103,
 517567208: 104,
 551023863: 3347,
 555553919: 106,
 512454070: 107,
 548760963: 115,
 513075253: 109,
 531206381: 110,
 515323037: 111,
 529549424: 112,
 523557833: 114,
 515353201: 116,
 555553089: 117,
 530233379: 118,
 520006641: 119,
 532126276: 120,
 513635938: 121,
 522193171: 122,
 518679812: 123,
 550260122: 124,
 539666901: 125,
 518617024: 126,
 547114477: 127,
 526870030: 128,
 522033917: 130,
 515299026: 131,
 551680852: 132,
 555565060: 133,
 519902438: 134,
 547025081: 135,
 555542171: 136,
 555514848: 147,
 517883707: 138,
 519951235: 139,
 537476865: 140,
 517472791: 141,
 517575585: 144,
 555579210: 143,
 540842449: 145,
 555147249: 146,
 515168801: 148,
 541184322: 149,
 514117792: 150,
 553373047: 151,
 543420389: 152,
 555586026: 153,
 546751980: 154,
 555585346: 155,
 529946464: 156,
 541188340: 157,
 514252765: 158,
 513163084: 159,
 540621528: 160,
 518853117: 161,
 542031282: 162,
 512653799: 163,
 516872593: 164,
 555344102: 165,
 513477743: 166,
 555608611: 167,
 555608887: 170,
 519278279: 174,
 520739919: 171,
 552695667: 172,
 538254255: 173,
 555613785: 175,
 518359482: 177,
 555621875: 178,
 544088428: 179,
 555625320: 180,
 555623251: 181,
 513305648: 182,
 555630258: 186,
 539483605: 184,
 522954573: 185,
 518317251: 187,
 520058577: 188,
 525695348: 189,
 537137730: 190,
 549348995: 191,
 541782016: 192,
 539074943: 193,
 544934190: 202,
 530397694: 195,
 518287521: 197,
 518463035: 199,
 521134060: 201,
 553290650: 203,
 524510079: 209,
 515405264: 208,
 543290590: 210,
 544131321: 211,
 540255045: 212,
 514088222: 213,
 547176785: 214,
 546130602: 215,
 514666711: 216,
 515325853: 217,
 517787467: 218,
 553700110: 219,
 525480164: 220,
 543566506: 221,
 554585492: 222,
 519288549: 223,
 514869860: 224,
 542151268: 225,
 554271272: 226,
 555678870: 227,
 555680872: 228,
 512596289: 229,
 545479245: 230,
 514150704: 233,
 544023456: 232,
 539733611: 234,
 522556942: 235,
 518882191: 236,
 522125649: 237,
 513233446: 238,
 531401327: 239,
 555682726: 240,
 555688662: 241,
 540386866: 242,
 513008215: 243,
 536399073: 244,
 514212703: 245,
 513604945: 249,
 547811542: 247,
 517116243: 248,
 516892571: 250,
 538339414: 251,
 541121600: 252,
 546527172: 253,
 535809166: 254,
 550840781: 255,
 518455823: 256,
 515397273: 257,
 513573014: 258,
 514531449: 259,
 531615955: 260,
 514872668: 261,
 543651486: 262,
 531588527: 263,
 513545468: 264,
 552519904: 265,
 544335888: 266,
 514045193: 267,
 518751525: 268,
 555272851: 269,
 514753709: 270,
 550398612: 271,
 540828135: 272,
 514748353: 273,
 514065899: 274,
 555212521: 275,
 520359652: 276,
 542310337: 277,
 523594878: 278,
 513204211: 279,
 555746348: 280,
 515244218: 281,
 525111067: 282,
 541770453: 283,
 517293800: 284,
 552867273: 285,
 542221436: 286,
 555727222: 287,
 514577571: 288,
 539273920: 289,
 549718373: 290,
 545124038: 291,
 514161976: 292,
 512710263: 293,
 514143099: 296,
 498360472: 295,
 553636175: 297,
 543280514: 298,
 545002240: 299,
 548477907: 300,
 555521943: 301,
 513529493: 302,
 555844413: 303,
 551315072: 304,
 512957342: 305,
 514438784: 306,
 548913793: 308,
 553537774: 309,
 522751744: 310,
 520055758: 311,
 552170733: 312,
 554424971: 313,
 555487933: 314,
 546177421: 315,
 517039024: 316,
 555858649: 317,
 513247955: 318,
 512463957: 319,
 555855504: 320,
 515505818: 321,
 543617092: 322,
 512779114: 325,
 536211062: 326,
 514917588: 327,
 514477354: 328,
 555873567: 329,
 516918674: 330,
 527436290: 331,
 555873431: 332,
 555874217: 333,
 518870680: 334,
 537867439: 335,
 548091445: 336,
 516798725: 337,
 555880262: 338,
 526630416: 339,
 555879957: 340,
 512932255: 341,
 512851304: 342,
 517476165: 343,
 512710221: 344,
 554753045: 345,
 555175493: 346,
 514315761: 347,
 538342915: 348,
 555897944: 349,
 527907597: 350,
 514960976: 351,
 555902377: 352,
 547856889: 353,
 539360081: 354,
 533853914: 355,
 530271581: 356,
 555901389: 357,
 545157048: 358,
 535198490: 359,
 513213430: 360,
 545634305: 361,
 514280795: 362,
 523328557: 363,
 513173658: 364,
 513190799: 365,
 513474724: 366,
 541422339: 367,
 517809532: 368,
 516011358: 369,
 516940987: 370,
 555919468: 371,
 544471432: 372,
 531219436: 373,
 555923860: 374,
 538780784: 375,
 553500356: 376,
 548837228: 377,
 527575421: 378,
 527415098: 379,
 521030180: 380,
 531733764: 381,
 548723322: 382,
 512996525: 383,
 543219033: 384,
 554275573: 385,
 520985860: 386,
 513731007: 387,
 555941016: 388,
 522823042: 389,
 515888511: 390,
 528297724: 391,
 552759541: 392,
 535847283: 393,
 517907169: 394,
 537426988: 395,
 555949074: 396,
 517560143: 397,
 541704927: 398,
 555948948: 399,
 519747830: 400,
 547216758: 401,
 555948501: 402,
 515317668: 403,
 555945223: 405,
 541724221: 406,
 545075462: 407,
 551556708: 408,
 536016365: 409,
 514911426: 410,
 530135199: 411,
 516010272: 412,
 512575905: 413,
 555960488: 414,
 535823636: 419,
 514379075: 416,
 516349362: 417,
 539495598: 418,
 514977937: 420,
 550231084: 421,
 520937641: 422,
 515476639: 426,
 533471508: 424,
 552703736: 425,
 513579140: 427,
 552055467: 428,
 512691674: 429,
 532546236: 430,
 555968414: 431,
 519549320: 432,
 555970068: 433,
 519123312: 434,
 540020772: 435,
 552460129: 436,
 514580396: 437,
 555974354: 438,
 513383412: 439,
 551778497: 440,
 518697106: 441,
 516272835: 442,
 512927316: 443,
 555526369: 444,
 534112343: 445,
 542114712: 446,
 553330196: 447,
 529072096: 448,
 541360466: 451,
 513885704: 450,
 522956722: 452,
 544018694: 453,
 552589944: 454,
 513519170: 455,
 513519855: 456,
 520057328: 457,
 512892356: 458,
 517722833: 459,
 556010815: 460,
 513715391: 461,
 514229373: 462,
 556010864: 463,
 556012914: 467,
 540847202: 465,
 556014482: 466,
 521797621: 468,
 514964513: 469,
 536057220: 470,
 524312724: 471,
 515709807: 472,
 513606687: 473,
 517054094: 474,
 544080041: 475,
 523151075: 478,
 525215792: 477,
 538871913: 479,
 542734627: 480,
 551695887: 481,
 516908074: 483,
 512589047: 484,
 556036059: 485,
 532490349: 486,
 556038065: 487,
 550447388: 488,
 556042122: 489,
 512833345: 490,
 518848591: 491,
 524252551: 492,
 516191499: 493,
 533096496: 494,
 549993487: 495,
 552956754: 496,
 548756281: 497,
 514085682: 498,
 518271664: 499,
 552353254: 500,
 550836103: 501,
 519883803: 502,
 542102998: 503,
 549731179: 504,
 556062501: 505,
 556066214: 506,
 529138487: 507,
 513248922: 508,
 545484663: 509,
 552774191: 510,
 549982595: 511,
 513320079: 512,
 554634385: 513,
 513691135: 514,
 514180893: 515,
 556073646: 516,
 556084045: 517,
 549458312: 518,
 524515945: 519,
 514350036: 520,
 532251961: 521,
 513980823: 522,
 556094628: 523,
 512680137: 524,
 531732958: 525,
 520176864: 526,
 512845340: 527,
 556106383: 528,
 541494455: 531,
 537759739: 532,
 535051188: 535,
 551478118: 536,
 535518630: 537,
 515064965: 538,
 529865066: 539,
 518282013: 541,
 533594914: 542,
 519674515: 543,
 536419161: 544,
 549831970: 545,
 548202419: 546,
 546731432: 548,
 556038281: 549,
 531549129: 550,
 513292093: 551,
 535404178: 552,
 533924427: 555,
 513032771: 554,
 514549763: 556,
 536268700: 557,
 554351664: 558,
 516143498: 559,
 548132538: 560,
 512718476: 561,
 529889789: 562,
 537103747: 563,
 554254095: 564,
 556004828: 565,
 530593185: 566,
 555958826: 567,
 513574473: 568,
 542363732: 569,
 556227542: 570,
 533202969: 571,
 514732859: 572,
 515603064: 576,
 556230204: 574,
 531360028: 575,
 518588546: 577,
 512590096: 578,
 555848041: 579,
 517475206: 580,
 524005080: 581,
 536000428: 582,
 512930904: 583,
 556238708: 584,
 537943247: 585,
 515016774: 586,
 555527292: 587,
 554408034: 588,
 520764653: 589,
 520373416: 590,
 512965859: 592,
 517574868: 593,
 556241311: 594,
 543112554: 595,
 556254098: 596,
 545773315: 597,
 537048580: 598,
 556256028: 599,
 555915069: 601,
 520869593: 602,
 540098104: 603,
 527916490: 604,
 514424300: 605,
 547324707: 606,
 556258374: 607,
 536841558: 608,
 515251964: 609,
 526903833: 610,
 526579862: 611,
 535980313: 612,
 515204375: 616,
 513193499: 614,
 549034578: 615,
 516054632: 617,
 524008970: 618,
 550333762: 619,
 516981051: 620,
 553598483: 621,
 513445144: 622,
 542326016: 623,
 556243270: 624,
 517116410: 625,
 556274698: 626,
 519198478: 627,
 552287767: 628,
 514950995: 629,
 526616620: 630,
 556285217: 631,
 556287099: 632,
 538245224: 633,
 553408507: 634,
 555204956: 635,
 524799009: 636,
 556288048: 637,
 517017194: 650,
 517911207: 639,
 514859666: 640,
 545167077: 641,
 545667679: 642,
 515644655: 643,
 548475795: 644,
 553672508: 645,
 544165971: 646,
 554376202: 647,
 541083769: 648,
 553660021: 649,
 524299883: 651,
 518643831: 652,
 512435259: 653,
 547024783: 654,
 526226992: 655,
 534867307: 656,
 512465037: 657,
 512461937: 658,
 512880674: 659,
 556309005: 660,
 519886154: 661,
 556308156: 662,
 518370548: 663,
 514911000: 664,
 531753610: 665,
 544819661: 666,
 524918279: 667,
 514700678: 668,
 551972153: 671,
 556314435: 673,
 517000200: 672,
 546835458: 674,
 517838353: 675,
 520088548: 676,
 512890684: 677,
 515940047: 678,
 525063476: 679,
 522042334: 680,
 513881639: 681,
 516938231: 682,
 515367946: 683,
 514709779: 684,
 530991619: 685,
 513815485: 686,
 540821164: 687,
 525041513: 688,
 515487836: 689,
 555235030: 690,
 553829906: 691,
 544674528: 692,
 521218170: 693,
 516644466: 694,
 527671752: 695,
 518590122: 696,
 556343679: 697,
 513072857: 698,
 518831663: 699,
 550514254: 700,
 516667697: 701,
 514712689: 702,
 514088577: 703,
 555301129: 704,
 556352859: 705,
 519962150: 706,
 512906834: 707,
 522558357: 708,
 514085599: 709,
 533916000: 710,
 556360124: 711,
 550554236: 712,
 515191058: 713,
 545270944: 714,
 546662878: 715,
 556359232: 716,
 525056695: 717,
 553147607: 718,
 519056531: 720,
 543091473: 724,
 556360683: 722,
 555975856: 723,
 554217298: 725,
 556374373: 726,
 515344729: 727,
 513088622: 728,
 512538895: 729,
 516830741: 730,
 550484614: 731,
 520869957: 732,
 549307225: 736,
 518325095: 734,
 516628060: 735,
 513883958: 737,
 530930049: 738,
 519236119: 739,
 518465644: 740,
 530410380: 741,
 521139443: 742,
 555821880: 743,
 547497582: 744,
 527557441: 745,
 513243521: 746,
 538197352: 747,
 542867779: 748,
 516308007: 749,
 556417648: 750,
 556411090: 751,
 548819328: 752,
 534548028: 753,
 513180668: 754,
 527400081: 755,
 556424203: 756,
 523192176: 757,
 549514548: 758,
 532942761: 759,
 539295881: 760,
 524159213: 761,
 556433199: 762,
 513432963: 763,
 513127135: 764,
 530259641: 765,
 532562049: 766,
 527227831: 767,
 537168813: 768,
 519053549: 769,
 513509756: 770,
 555549729: 771,
 515742881: 772,
 522090078: 773,
 516744200: 775,
 556465033: 776,
 555941320: 777,
 554242326: 778,
 516687377: 779,
 522410486: 780,
 518636596: 781,
 553858559: 782,
 536357728: 783,
 533547494: 784,
 556477116: 786,
 556481314: 787,
 513908347: 788,
 525006138: 789,
 556484406: 790,
 512425313: 791,
 556413497: 792,
 521895428: 794,
 534072070: 795,
 556491047: 796,
 514068032: 797,
 518395104: 798,
 540074715: 799,
 556514549: 800,
 513682217: 801,
 556066022: 802,
 513522691: 803,
 550379356: 805,
 516534350: 806,
 546761208: 807,
 513267764: 808,
 521758029: 809,
 555304917: 810,
 523512174: 811,
 553270521: 812,
 530100082: 813,
 549151329: 814,
 512462154: 815,
 536414944: 816,
 512570414: 817,
 517925422: 818,
 555089002: 819,
 544824094: 820,
 556099594: 821,
 556453923: 822,
 553538349: 823,
 556577948: 824,
 513267110: 825,
 556575346: 826,
 512984809: 827,
 530865002: 828,
 541659360: 829,
 542356970: 830,
 518924493: 831,
 553048523: 832,
 514889175: 833,
 521558486: 834,
 545555492: 835,
 520042828: 836,
 514452961: 837,
 512812480: 839,
 512783711: 840,
 513851877: 841,
 512367362: 842,
 513246358: 843,
 523097249: 844,
 517294938: 845,
 445228646: 848,
 536298061: 847,
 512658392: 849,
 523560481: 850,
 514319075: 851,
 519423088: 852,
 517794237: 853,
 513391455: 854,
 525143362: 855,
 519188801: 856,
 555711337: 857,
 523007334: 858,
 514889691: 859,
 526615994: 860,
 538854878: 861,
 556602638: 862,
 556602101: 863,
 528418616: 864,
 519439367: 865,
 546894081: 866,
 556604908: 867,
 530380620: 868,
 542627503: 869,
 534787456: 870,
 556606145: 871,
 513652993: 872,
 513505373: 873,
 517465797: 879,
 534908399: 875,
 517530378: 876,
 554476140: 877,
 548229764: 878,
 540656998: 880,
 521468988: 881,
 513853609: 882,
 542773881: 883,
 514115334: 884,
 512456312: 885,
 543052540: 886,
 520787472: 887,
 550142718: 888,
 556612581: 889,
 514194138: 890,
 513370080: 891,
 517918312: 892,
 514099480: 893,
 512365547: 894,
 556623808: 895,
 552841225: 896,
 513123413: 897,
 518753682: 898,
 555645605: 899,
 533615309: 900,
 556629070: 903,
 556012720: 902,
 512948092: 904,
 542375106: 905,
 512426335: 906,
 556634410: 910,
 543863893: 908,
 536100808: 909,
 535189300: 911,
 518507236: 912,
 513126947: 913,
 537193883: 914,
 544265249: 921,
 523910164: 916,
 526000692: 917,
 551775783: 918,
 556642399: 919,
 536167684: 920,
 520468594: 922,
 517425359: 923,
 546108502: 924,
 548087092: 925,
 555566031: 926,
 513592171: 927,
 529783339: 928,
 556644200: 929,
 556613916: 930,
 531367310: 931,
 515758569: 932,
 514503266: 933,
 515771847: 934,
 530789358: 935,
 519290392: 936,
 543941371: 937,
 554116967: 938,
 556661993: 939,
 553181728: 940,
 514914296: 941,
 514525691: 942,
 537325080: 943,
 547410786: 944,
 541500328: 945,
 537830542: 946,
 536609167: 947,
 514585058: 948,
 525364426: 949,
 556669658: 950,
 553396735: 951,
 519525927: 952,
 516281537: 954,
 553652547: 955,
 514944777: 956,
 544037202: 957,
 556673496: 961,
 515935384: 959,
 518472626: 962,
 514038655: 963,
 512872078: 964,
 556675602: 965,
 556343690: 966,
 523740492: 967,
 518662687: 968,
 518880849: 969,
 515463581: 970,
 530573128: 971,
 522610399: 972,
 513599503: 973,
 512402999: 974,
 542399106: 975,
 518939025: 976,
 556685104: 977,
 523638402: 978,
 513581293: 979,
 515771371: 980,
 520598165: 981,
 523975516: 982,
 554057970: 983,
 553193511: 984,
 516494454: 985,
 522309336: 986,
 553446229: 987,
 513691643: 988,
 540866072: 989,
 531601360: 990,
 536029513: 991,
 512592594: 992,
 520394712: 993,
 535231621: 994,
 525592869: 996,
 513082603: 997,
 525165037: 998,
 513336264: 999,
 556696328: 1000,
 523147423: 1001,
 553509727: 1002,
 549028299: 1003,
 550756834: 1006,
 516191164: 1005,
 551821591: 1007,
 541428182: 1008,
 512806902: 1009,
 556706040: 1010,
 522884167: 1011,
 516056241: 1012,
 537392563: 1013,
 556708411: 1016,
 513364685: 1015,
 515290686: 1017,
 538872421: 1018,
 516022928: 1019,
 542917019: 1020,
 516996492: 1021,
 515231144: 1022,
 514123060: 1023,
 543991400: 1024,
 512650236: 1025,
 539508820: 1026,
 554587546: 1027,
 523810302: 1028,
 515859470: 1029,
 542713862: 1030,
 550382846: 1031,
 543412150: 1032,
 519234957: 1033,
 513700401: 1034,
 556718939: 1035,
 513225794: 1036,
 513867029: 1037,
 542692556: 1038,
 534518774: 1039,
 515418110: 1040,
 556722503: 1041,
 556721972: 1042,
 514561144: 1043,
 556661180: 1044,
 519231908: 1045,
 543664701: 1046,
 539226767: 1047,
 514643749: 1048,
 556332965: 1049,
 555716873: 1050,
 522093443: 1051,
 550699580: 1052,
 530986310: 1053,
 512890245: 1054,
 514656595: 1055,
 513768664: 1056,
 517241729: 1057,
 533359160: 1058,
 518757423: 1059,
 528335075: 1060,
 527631505: 1061,
 519526155: 1064,
 516779640: 1063,
 556736882: 1065,
 555606722: 1066,
 513963354: 1067,
 512824921: 1068,
 544341179: 1069,
 ...}

In [29]:
idx = category_id[523117953]
sim_scores = [(i, c) for i, c in enumerate(cosine_matrix[idx]) if i != idx] # 자기 자신을 제외한 유저들의 유사도 및 인덱스를 추출 
sim_scores = sorted(sim_scores, key = lambda x: x[1], reverse=True) # 유사도가 높은 순서대로 정렬 
sim_scores[0:5] # 상위 5개의 인덱스와 유사도를 추출

[(29, 1.0), (46, 1.0), (67, 1.0), (84, 1.0), (92, 1.0)]

In [30]:
com_once.loc[com_once['user_id'] == 523117953]

              category_code     brand  price    user_id subcategory
1  computers.components.hdd  kingston  66.67  523117953         hdd

In [35]:
com_once.iloc[[29]]

               category_code   brand  price    user_id subcategory
29  computers.components.hdd  apacer   24.2  517465372         hdd

In [34]:
com_once.iloc[[46]]

               category_code     brand  price    user_id subcategory
48  computers.components.hdd  kingston  38.32  517010638         hdd

In [33]:
com_once.iloc[[67]]

               category_code    brand  price    user_id subcategory
71  computers.components.hdd  toshiba  39.02  531895455         hdd

In [32]:
com_once.iloc[[84]]

               category_code   brand  price    user_id subcategory
88  computers.components.hdd  apacer  34.75  518667476         hdd

In [31]:
com_once.iloc[[92]]

               category_code    brand  price    user_id subcategory
96  computers.components.hdd  seagate   66.8  550318201         hdd

### computers 유저간 추천

In [36]:
tfidf = TfidfVectorizer()

# Fit 후 dtm을 만듭니다.(문서, 단어마다 tf-idf 값을 계산합니다)
dtm_tfidf_user = tfidf.fit_transform(com_once_user['user_session'])

In [136]:
dtm_tfidf_user_df= pd.DataFrame(dtm_tfidf_user.todense(), columns=tfidf.get_feature_names_out())
dtm_tfidf_user_df

,0002,00025dab,0002c5ea,0005,0006bf97f732,0007ab79ced4,0011,0012d784,001312a0142e,00153b60a6e5,...,ffeb,ffed,ffee,fff6,fff60634,fff661e40162,fff9,fffa,fffac901e3c9,fffc
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9120,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9122,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9123,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9124,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
cosine_matrix = cosine_similarity(dtm_tfidf_user, dtm_tfidf_user)

In [38]:
np.round(cosine_matrix, 4)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [39]:
user = {}
for i, c in enumerate(com_once_user['user_session']): 
  user[i] = c

user_id = {}
for i, c in user.items():
  user_id[c] = i

In [40]:
user_id

{'63de1120-9d48-45d0-b024-500d1b95d71f': 0,
 '629a0485-36c9-4a80-9f02-4a96382c3059': 1,
 '56272bb8-9f35-4412-9f15-624c8ecda0f1': 2,
 '8d2582ff-8031-4b06-819b-a653eb1cb832': 3,
 '5622db13-66d1-4167-8bfa-b4f184aed29a': 4,
 '739c3ef2-012f-41b7-8450-01ca3866d6ff': 5,
 '0f65dee0-ae4d-460e-bb66-3da1bbbaec6b': 6,
 '9b9cc736-3daf-4451-a2d5-05c53011c2e5': 7,
 '5cfee4a3-d064-471e-a580-503dae0b490e': 8,
 '3a8a2e45-3c9b-4d1a-868f-9fb732f91bab': 9,
 '933010d0-2c90-4adc-a161-ec953aa99b91': 11,
 'b610c284-5924-4211-932a-340f98c1c700': 12,
 '52fad75b-1e60-4dec-bc22-a51d3d5680ae': 13,
 '5a14310e-3c18-4383-b584-7f56aefcd535': 14,
 '970f59a8-9af7-4fa0-bbbb-d81e7146ab9f': 15,
 '01d9b508-1e1d-4ca8-8403-d7962eaf34b6': 16,
 'e874dc74-0630-4b3a-b049-9dbf53d745c9': 17,
 '1fcdca81-f119-4556-b044-0d7a24fb7b61': 18,
 '7eb1c0d9-4b45-4682-bf26-c650b6d8c8fe': 19,
 'a31d70d9-ea3b-4b04-b247-9368618f8b2b': 20,
 '5ac10175-3214-4b5f-8906-2db4ef9bedcb': 21,
 'cb6a8583-b035-4d76-8583-d3a8ee969020': 22,
 '7e5ba25e-98ef-42ff-a890-3659a50ed7fb': 23,
 'a90189c0-c0f8-4ca4-be52-afe2202720be': 24,
 'b3bb7105-adda-3e8c-9a3a-f571f9b4024d': 25,
 '9364b489-6e14-408d-a7c7-39bf1c336e86': 26,
 '64667eae-7e61-4493-a9f0-866187b61f39': 27,
 'c3a11276-fc2d-478b-aae0-0b47034be14e': 28,
 'c98f69e7-a2a7-4595-8fa5-576ca4f5106d': 29,
 '786a28d5-ed7d-4c00-a1d1-7be88179bbd1': 30,
 'e5ea92d6-e819-4599-93b4-457ebd93cb57': 31,
 'efd5a1fd-5508-4e9f-b3ff-9b2aaeeb2d97': 32,
 'e51e0bd2-1790-4648-88a4-ef6538b31aae': 33,
 '4e7843ba-ce1a-46e2-a8d0-6ed9130dbeb6': 34,
 '70b6e96a-2a81-4812-a3a0-67bec1b280bf': 35,
 'd964a5a1-2947-4f6d-9fee-85ea53595869': 36,
 'c3593587-d10e-45d1-8bd5-be5e299a33f6': 37,
 '82db5606-2224-47a5-a431-fd017c35e479': 38,
 '35084d4a-2d46-49d1-8ce7-ef027db01e91': 39,
 'e8500322-7157-4334-ab82-28dd2f859b0c': 40,
 '7e516137-2fbc-4d68-b328-65855db26e60': 41,
 '51fb9a99-c65d-41f3-927f-589b89b87881': 42,
 '97c19e28-809f-4d5f-ace6-7680e31c6f98': 43,
 'bfc97135-f5a2-45e0-9877-eaaed0a979c8': 44,
 '64aea8c2-17ba-4af0-b390-fb0a1ab35980': 45,
 'c67ef2b3-3b51-48e1-9c10-298ed8cc5594': 46,
 '2b88d92d-5bf9-4312-b032-2390364191aa': 47,
 '6ef2f258-48c3-40cb-a88e-f152ab96c32f': 48,
 'de851660-4593-4398-930f-11b33d818fa5': 49,
 '0002c5ea-3509-4d0b-9618-7e40925005f0': 50,
 '794d3910-28be-4143-9ff1-608fcd2cad10': 51,
 'aea1090f-ca90-4697-95db-b447faf62309': 52,
 'a995e105-3819-4f20-b61f-6324b62e2093': 53,
 '2b5b0c8e-5b81-489e-adf2-c87c068fb74f': 54,
 'fa58ea69-e115-476e-895c-a6ef91459a3c': 55,
 '52b8f944-4d26-41c7-a019-d327df4fd78e': 57,
 'dfc06780-a518-4de3-a6f7-d20ba6d9217d': 58,
 'faf53dea-6f4d-4782-aac2-3380ada22711': 59,
 '22d95689-7bf8-4cf4-a084-ae84f6b28927': 60,
 '128a8d25-ff6f-4b8c-9132-38cc1403ed6b': 61,
 '2a254fd6-d5ed-46e8-a448-9e1062516c73': 62,
 'c4dc87c9-ab19-4a0e-ae24-81ab9b63e2b2': 63,
 '3d1574dd-7225-4968-9c86-9b4ef694eba7': 65,
 '3cff1df9-f238-455e-8fde-362bf6b19f9a': 66,
 '98fc6737-15ac-496a-8b4f-6e4c6dd248cb': 67,
 '49262533-f89c-4a8d-8ad8-973b724ce598': 68,
 'bcaaa591-c75f-4136-8d9f-c5f71762f2cb': 69,
 '2a953a30-c527-42d5-88e2-7091459b4a38': 70,
 '7a6f6ec9-77db-4bff-848d-e9f39ccaf98f': 71,
 '0907e7b7-5052-4fa9-89c4-aafa52fec52d': 73,
 '385b4c6f-eaac-4e8b-85f6-0a500d4691cd': 74,
 '84b69d3d-c371-46d1-8e12-af359ab1ac2e': 75,
 '525684e2-fdf2-4166-a4a8-52885b54fdb9': 76,
 'e271ab50-fa43-4e4c-8da5-4a1a33f8dee9': 77,
 '0c602f52-f1d2-4f3a-91c0-b1caa6485f9f': 78,
 'cd15dbef-c77d-4917-adf7-3a5452822db7': 79,
 '12114083-c6b4-4e09-8b95-609625fd1361': 80,
 '0cc7e85e-6062-47ee-bc24-13f82dd7af06': 81,
 '26a28be4-6587-435b-bb81-6b3ce534d935': 82,
 'ab5b1bed-d38d-4a6a-8ebc-c60e27055eec': 83,
 '7799e933-7a3f-4559-88e9-c701f83f3862': 84,
 '7d691c7d-1350-4aa4-b441-953db040edd5': 85,
 '25feaaf1-ad26-407f-90bf-44954d34ac93': 86,
 '1da83632-795a-4045-a78d-eb90e8ba7968': 87,
 '51fdd45f-c856-623b-0b1d-e69dd35bb64e': 88,
 'bf384172-81a3-421b-9fb5-4e7b260a528d': 89,
 '77b5baca-9f85-4d49-bca9-bad902bbfdec': 90,
 '8bf12da3-f813-49d1-acb6-1c2328b02f6a': 91,
 '55b7a38b-0607-49e2-8733-a412184179b8': 92,
 '2abf1393-6db8-487b-8cbe-49ab7ab12e00': 93,
 'eef8f96b-35c8-4c09-b22a-e84bdf9760ad': 94,
 '41eaeca5-8d3b-42e8-8ef5-2ddd056d9e9c': 95,
 '8ea535d5-e0c2-4b58-a552-32f05a41d1f9': 96,
 '2dabbcff-e540-4e9f-a420-718edcf09837': 99,
 '1562f48f-ff04-40b1-a747-2e0bc92a8bd4': 100,
 '45c31954-5340-47ce-b584-89554ed190d3': 101,
 '43773ac7-b14b-414c-bdcb-f706e963382d': 102,
 '45d36b19-5a27-42c6-8f0e-a76a832e8d1e': 103,
 'febbce6f-fb37-4c66-9cb4-7be38e427091': 104,
 '38798848-b4c6-4a9e-9cbe-592e342518e0': 3347,
 '8857979e-afcf-4964-8089-7ec5087b7f2d': 106,
 'd9ce4d11-27df-4af3-8a05-dbc29ae38cbf': 107,
 '727be3db-c938-4a87-972d-057b0e49c58c': 115,
 'b1e3ebcd-6137-44a1-8f4a-59668648eaf8': 109,
 '61c5f8fb-e835-4f20-893c-cd129d1e0c4b': 110,
 '166ac6be-0fea-46fa-ae0b-0771e58df4ac': 111,
 '5ec45c3e-c322-4b9d-9b0f-813a51b17f20': 112,
 '89fa7bce-6e2d-4fd0-ae9a-47b3f9217daa': 114,
 '03b1c713-5b20-460d-b210-d79058e4786f': 116,
 '1c4185e1-87de-4669-b952-588ab1d44567': 117,
 'b1e69b44-0415-4659-b60d-1295bcd867cb': 118,
 '2a7ab879-7f4e-43ae-b354-7bea173f4593': 119,
 'b41df01e-52f3-4891-a41c-a059f952272f': 120,
 '8bcaed0b-9f06-4d2f-92db-6c2dff5531af': 121,
 'ee2b65bc-7d1e-4598-b331-68479e723cf4': 122,
 '6e19913a-f4f3-4d17-bdcf-9acad551a018': 123,
 '399a490d-3955-4088-ab50-6774fe85b1ca': 124,
 'cf02aee8-18e0-4ac7-a160-fcdbbc4b193e': 125,
 'f5b48eee-4edd-441d-95ef-c06f1711f7e8': 126,
 'd81e0c88-9918-4012-8a1a-78efdd959df4': 127,
 '154a2fb1-6a54-41a9-a493-9db0ac2ee104': 128,
 'c5912c96-3f24-43c9-b63c-9cd892876f96': 130,
 'aa314b7d-031a-4305-820b-d991618eb872': 131,
 '4ae12b61-5653-40c2-8850-bfa2b27ce77a': 132,
 'de45eb3f-da92-44ab-ad24-9db9a73c8aa2': 133,
 '2f2988cc-7364-4e20-b0a2-201526193377': 134,
 '90100f7e-5221-45c7-96cc-103f964cb1c8': 135,
 'f4490bc4-b5f9-4cfa-abc9-d910316920fe': 136,
 'd0153fb5-d023-42c4-a28c-c0e6075a7c82': 147,
 'd1511072-805c-45bd-955c-aca4300a557f': 138,
 '843f5d6a-7919-4f15-9193-cd48e47d193a': 139,
 'a9ba94d4-5dc0-43dc-ab97-0d8759f5c674': 140,
 '239323c6-6c1d-4c02-ac35-cdf32a0dba49': 141,
 '99da61af-a0a4-43da-a45a-7923bdc913eb': 144,
 '40b8c2f3-006a-432b-8f4c-ef36a00ec744': 143,
 'ac2641b4-e79a-45bd-8aeb-6ea86e70dfea': 145,
 '907c4807-6bd5-427c-bf9d-f76855ad0f00': 146,
 '53b8c0be-3440-453e-941f-b0ad762a14f5': 148,
 '2b720f96-7902-4294-a918-070f9a15e9d7': 149,
 '2b0ede04-5a65-44a0-8398-657e34e5865d': 150,
 '1e192d1c-f5af-4420-9cda-76739ce632ac': 151,
 'c029181b-a1c6-46f8-9969-3deaf9807942': 152,
 'f3394e31-f470-439f-a256-c10db3a3c412': 153,
 '15ab3b29-463f-4b33-ba4e-227e80d88631': 154,
 '4d79c6d8-b2d3-48a1-bf67-b2b3a9fe66df': 155,
 'd39c5358-0023-4d27-bd19-8b8225d4c80a': 156,
 'df47910d-f931-4a65-b568-435e23eb63fb': 157,
 'da193a3c-8801-4e3c-a163-057dab8a1b5c': 158,
 'f856d979-1b50-403e-9c7e-764e74fd7850': 159,
 'f7ed9a5c-6a5e-42ec-b985-5e25d45e86f3': 160,
 '9fae3ff4-b9e8-4ee8-8bd1-6b25bd213204': 161,
 '3af85508-b54c-49da-84aa-15af1941e62d': 162,
 'b1602820-0230-476a-821c-7d33ebae7e9c': 163,
 'be786336-ec1a-400e-8f47-8f5d9f757e81': 164,
 'a0a72a31-12c3-4853-b91d-50aee1b24ede': 165,
 'd87ae247-95dd-43ed-b5c9-f010fd4fb00e': 166,
 '8848dfe6-0a2a-4638-97ac-a9cfce90e295': 167,
 '3da9f702-7aa9-418d-a575-bae60c1e05bb': 170,
 '93381d75-d454-4476-9e5d-bb4e2bec44e9': 174,
 'bb7a636f-3bda-455e-989e-35f1470959c4': 171,
 '49831d2f-f8c7-4680-9f0c-299583775dac': 172,
 '4257dcc8-5fa8-41db-bea1-368a85bc4496': 173,
 'd77cfab5-1279-4051-ae84-ba3ac2002dae': 175,
 '1706a34b-ee12-47d7-9f39-ed07949e262a': 177,
 'b48732a6-fca5-4bb8-8a74-5887b36c2cf6': 178,
 '9da06c1a-c6cf-471e-8c5b-eaf7a8c2f3c6': 179,
 'af57a579-d7d7-4078-a9e0-e0c9e191f77c': 180,
 'ab6d59e3-df72-4682-9d12-8cd1d923f376': 181,
 'c2078460-509d-4235-a2a5-7f95431567ed': 182,
 '0bff77c8-4dfb-4066-915c-9330c5970611': 186,
 '8fa0dd38-391e-42b6-87c4-89b4525682eb': 184,
 'f1c514d5-a99c-414a-933c-ccef0608d8f1': 185,
 '60dc3bda-9f3b-4252-b45b-4476f8c89f40': 187,
 '0c580411-6c61-4443-a7d0-63b750fe69c1': 188,
 'd5f27477-0f91-4e64-b385-602ce3c56edf': 189,
 'd26191c3-eeea-4084-ba83-e10ce8893928': 190,
 '27e3aa4a-41c1-484c-b541-0fa5830789ce': 191,
 '31db5be2-a715-434c-9e38-59f1f5e19275': 192,
 'cac86615-d6d3-4275-a9bb-f621bbb86561': 193,
 '7e53d459-d032-4b4f-bc64-b44bb2553386': 202,
 'df30a5ea-e30c-491e-94fb-51841d2d501d': 195,
 'a51bdfd1-0bc5-4ace-be2f-134ee9a7815e': 197,
 '52cc9ac0-f6c3-44de-81e6-458e0ebffdd8': 199,
 'f73e5cec-871b-485d-a825-d8b0eb18a086': 201,
 'b40c4e3b-0c45-41f1-814e-c0e9d54cf0b6': 203,
 'f47aa891-bd04-4a7b-b8e8-7107f676dc97': 209,
 'e216416f-bcad-411a-95a6-f60f80b3469e': 208,
 'd9f239e5-310e-4010-b37a-951ff0a77599': 210,
 '71744f33-a01c-4369-accf-98c0128a039c': 211,
 'b37fc7c0-66b5-41cc-b278-b7bf67107229': 212,
 'f2ffe909-ddd6-4d33-896d-9017d253ce26': 213,
 'add5f606-adee-40a4-a052-b7741ded9d70': 214,
 '22c87f4a-3104-4b96-b1a8-68c26ab4a811': 215,
 '839dc6d7-ef20-4d6f-b591-f513f805a579': 216,
 'b7ff96dd-d952-4611-93f3-182d99be142c': 217,
 '5e4ba05f-0b44-4604-bae0-bbfe55a43b43': 218,
 '2aa20f0a-a4a9-4d98-a38f-3551425ca35a': 219,
 '03903293-87ad-4c08-9b7f-66b734c995cf': 220,
 '8a40d32b-5dd8-4834-9e89-2dd307e356dc': 221,
 '60f7972f-1ce3-4af6-bbc1-ca29982dbf80': 222,
 'f15228ac-39ce-41f1-a9b9-a7ffbb013f11': 223,
 '0c6ffa7a-fabd-4397-86bd-e605890f72a0': 224,
 '99ba14c3-bd2f-4efd-856a-0db1796b949b': 225,
 '340d9a98-8994-4b51-bfe5-8e78b77d8032': 226,
 '4029e6d3-6806-4e0c-9d0e-b7d8b66637f7': 227,
 '6c0af34d-d241-4793-8c4b-0b12d72b0e90': 228,
 '97206079-5966-4201-bb0b-24a54797df02': 229,
 '22237a29-0664-4545-a72d-d1f36e1e288e': 230,
 '41d25546-8a34-45c5-aede-1272a9eac7f8': 233,
 'b55cfcfe-612f-4b3d-85e5-64ecd2b2ef82': 232,
 'f86d2bd9-6249-4c50-86e0-a4055d217e51': 234,
 'b9d4f864-f089-46ef-9dd9-bef2c9040063': 235,
 '3c3cdbee-15a9-443c-ac14-0b824966e9e8': 236,
 '5f6cb2ae-db20-4128-a31d-6215eff1552e': 237,
 '56f8d9bc-f854-4e5d-8545-1540ee2c0bbd': 238,
 '443014c4-226f-4a95-82a5-fc90593ae611': 239,
 'b659b807-feaa-43b9-99a8-ecfa8c5f7d06': 240,
 'e44d790a-0005-4227-9222-f5fb03982773': 241,
 '1d55e43f-1d9d-46d4-ab0a-9a45b2cec90a': 242,
 '3ecc1eaa-3a04-4332-875f-0ad9ddd1bb94': 243,
 'dd744845-7840-4b0b-a7fe-1a3b0c434ae2': 244,
 '855b896d-455c-4519-8f6d-6e3221fbc4f4': 245,
 'e53fe5c7-a82c-47ae-a842-3085be14e628': 249,
 'cb7f3a5f-2c71-453a-a5c5-8a5673145ca5': 247,
 'f3f93415-8bf4-4f73-8e3b-ca425d6a43a1': 248,
 '86920fc9-1ed8-4e02-9083-0b35919136d4': 250,
 '7bd5b1d7-6ee8-4fc3-876e-a599e6d4e37e': 251,
 '2d524e11-3230-49e0-90ae-a9e8fb6dd9a0': 252,
 'a58af900-9b2e-4edd-a14e-a58ae1738c71': 253,
 'ab054715-cbea-44d4-9640-f391c39d4b3e': 254,
 '42747073-3f21-41e7-b172-289f5bb22dba': 255,
 '763343c9-21cc-41b2-9b23-60152782e2ae': 256,
 'b0e5eeaf-4f36-496d-8d4a-ba9b405ba77b': 257,
 '22ed7f6d-04fc-40e4-8a46-a600d42c6f8a': 258,
 'bd287854-a6e5-4143-bfd4-49ec4c46c87b': 259,
 '0a47d5fc-c34b-4635-a95e-f90d4022eb7f': 260,
 '400a5c62-42af-45bf-9274-d2239a1107b5': 261,
 '4a00d527-30aa-438b-b13c-a3ddcbd1db2d': 262,
 '84b8ffc4-6983-496e-9953-c412de1ab62a': 263,
 'fd9a9bce-8c73-4ae6-9188-809bb0dc3ecc': 264,
 'fb1e783b-8931-4b29-b66f-2f98f899ee8c': 265,
 '234aa9a6-bdb9-4ce2-92ac-d5d3b79dafc3': 266,
 '24669b6c-2ab4-4065-aa7e-ea30dbfef68b': 267,
 'edbf21e9-7f24-4f71-9f67-cfb987e17d34': 268,
 '4d1d0151-8468-4c8f-9419-8210a7471647': 269,
 '09930feb-4990-4c47-b9b1-88255b7a0280': 270,
 '4eec739e-484a-49b7-94b6-8798a0ee10ff': 271,
 'a9bc2d68-5397-41ee-ae91-1404854cfb55': 272,
 '608ae6a6-e637-4d95-958f-bec11e9b1c9f': 273,
 '7adf00d2-5643-46d4-8912-ed08f1511efe': 274,
 '42271d26-2dba-4933-8572-aae3e10d9be5': 275,
 '6ce60305-ad91-4d58-8f43-192e2bb5e35b': 276,
 'f86546ae-1872-4227-a5f0-bf98d6aa4f79': 277,
 '9684ba43-9a57-423f-8c90-579e9deacd23': 278,
 '4263023e-54e5-4fb3-bb51-75e86b2d95f6': 279,
 '6ee9580f-b518-486b-934c-562095571303': 280,
 'd2791dfa-7ced-4a6f-9711-5fb130c5186b': 281,
 '5cdbefdc-e6fd-483f-a51e-00514f14e490': 282,
 '9bb87f20-6574-4557-bec0-f880e501ce8d': 283,
 '39b4b80b-a390-4b7c-bdc7-6549efa145a5': 284,
 '2d017e31-8601-4779-a779-ebd2cff0065d': 285,
 '838b3c11-6fab-4608-9c8c-eb2eb0e4038c': 286,
 '3c15e706-485d-41a7-98cb-974bca696aeb': 287,
 '2fcfbf04-f4f2-4ac1-bdb5-c68db4c13c58': 288,
 '0c7d9573-3c67-4651-b683-d3438ba8aa72': 289,
 '26a05ae0-ff12-42e4-a180-e985e4ced7ec': 290,
 'db633a37-bb04-4591-bf7f-3018bd7501e5': 291,
 '9e6992a7-9ffd-4c84-bbe0-fef13f545a17': 292,
 'b38df5cc-37d5-4ba2-a30c-fee21ad97fc7': 293,
 'f3fede41-bad0-46ea-8f05-1eef517c21e9': 296,
 'b8c5c92b-1677-481a-a1a7-01141fed7f44': 295,
 '6eb99064-aa3f-4fa7-9810-d5fe23172f49': 297,
 '857ed556-4561-467c-898c-62d877ebffbb': 298,
 '21a29fcf-6715-4de4-8c9d-bfbd90b2ab93': 299,
 'a8e55144-2163-42b1-84f4-251dcb928203': 300,
 '0a4d71aa-7a09-43b3-a907-e515cadb3159': 301,
 'fa9ad724-547d-4969-b433-eb50a86397c9': 302,
 '3d646454-840c-4246-9ceb-15543867140b': 303,
 '41bc6344-f7c2-4ff5-87e7-b7ad1c6ea692': 304,
 '605f4a47-76e7-4329-b4aa-362a020a61f3': 305,
 'f4ff7e0b-b2c5-43b3-927c-68083352a097': 306,
 'c7e413da-a8e1-4f49-89d5-539851fc3fed': 308,
 'ce77b264-a6fb-441b-9f10-0c96011213a1': 309,
 '9ca36c89-b8bb-454d-82ba-56fd43d96e73': 310,
 '27f430f3-1bcd-4c06-8ed6-9bbae3286022': 311,
 'b3affde2-7ec8-45ee-880f-c25e2a021c6b': 312,
 '6be73aad-ade0-4d4e-baeb-63789aebabea': 313,
 '721ffae7-e6b8-4331-888a-8fd69661fbbd': 314,
 'd9d7234a-e512-48f3-9432-51f82880c0e0': 315,
 'd4f22e87-dafc-4d6a-88c2-5ce712be1697': 316,
 'de0e2f66-f43a-4b58-9380-3d8cbc24d901': 317,
 'a5ef331a-b713-45fa-9609-1189965ffd85': 318,
 '57d98cfe-8e3b-4e4a-b7ae-a000d05b661d': 319,
 '241e1318-a4a2-41c1-8fd2-0510937f8219': 320,
 'eda7b473-fe3a-4b87-8b47-ae9841eb16eb': 321,
 'b8ab66bc-ce22-4c6b-b1a8-f4ec3ef81ffd': 322,
 'aab5fed4-7cbc-431d-8687-0627f12217e6': 325,
 'e3d5e813-fadc-41a8-ae09-3902ad886b79': 326,
 '911d3b59-3360-4c73-b051-e70726fa2597': 327,
 '30762448-6d6e-45a0-97da-efcaa82fe01a': 328,
 '5a8531bb-8168-4557-9e8a-31dd40f34cc2': 329,
 '57f10460-6f8a-4fdc-8622-1b1290b71627': 330,
 '711cf4be-b30b-4953-ad8b-762506c48ed4': 331,
 '0baff6c6-f164-4d6e-b2e7-c37039d528ed': 332,
 '4de55513-4228-4f70-8589-c43c001a91e1': 333,
 '060a94ab-81a1-4fda-8e05-9276d6a713f3': 334,
 'dc9779ad-ee9b-4c56-bd43-37d977f6db33': 335,
 '4c28b90e-0204-455c-bf20-c68d6015a387': 336,
 '90543617-3a8b-488d-a5a5-f5f7ef1f3409': 337,
 '15aae952-0516-4c31-8301-516d63b29eb2': 338,
 '62d885c8-bc77-4756-837b-fd5058d2eee5': 339,
 '57594db6-3b3d-4617-8e16-0b84da652ee8': 340,
 'f70af242-2d8f-4382-980e-804f158a8b29': 341,
 '6f519ec9-b1be-4583-a646-0f24131f8235': 342,
 '6804112a-ac19-4892-939a-b1771d998bab': 343,
 'dbb9d0dd-3e5b-43d9-a4d0-f12cd9c0251f': 344,
 'f267d940-b9e2-4dd6-84c8-903559de7d3c': 345,
 '32a4dc46-bf4e-4a15-8ec4-58980d345c39': 346,
 'd8d1b767-c326-4bf7-b3af-a7544b67c92f': 347,
 '0eeed3db-3a03-48ed-848b-2ac3433a3b71': 348,
 '07366c53-2d84-4e02-9c93-7dd526a2a2d4': 349,
 'd4204e1b-cd8b-45f1-bf8f-77baa58dfaa2': 350,
 'e046b37b-03db-4d59-b280-525f30972a0f': 351,
 '1b089642-3ae0-4293-9a22-909523761981': 352,
 '21f45b62-7434-43e2-80d7-85df682f13bf': 353,
 '720c228f-fda0-479a-8668-e11877315831': 354,
 '1fd71c57-d6e2-4ea5-b155-06e5916be775': 355,
 '1aa087c8-cbfe-494c-a651-1186691d35e2': 356,
 '51f33f97-5204-43f3-90ae-5e33c3f2d91c': 357,
 '0eb9e7b0-f6b4-435c-8e97-66af395a4f0f': 358,
 '1f394f90-60c9-41c1-b909-602d854c47c1': 359,
 '0828dad4-9470-4a4b-b6df-98c9e97620aa': 360,
 '79aa8983-4676-4b7f-9082-79928ff101e7': 361,
 '7ca6627d-4089-4860-b95a-c364903953f3': 362,
 'a37ccf86-52c2-4cf4-9638-c3ab9c6133fc': 363,
 '49eae19f-d1ea-4c48-a367-4896da1d3bf2': 364,
 '00c6e6e2-1ce7-4f1c-887c-434096374901': 365,
 'b52bdb24-fe2d-42ed-b7b2-48e7fa5b593a': 366,
 '1c917203-c2c7-43c3-a1b0-18c3780a29bb': 367,
 '87bf2241-007c-4a4f-85e8-573c88cd7e78': 368,
 'bb6de589-9326-43b4-9902-c87f7ea1e660': 369,
 'ddd015ad-0068-47c2-807f-c0995acee76c': 370,
 '0ccd1120-adf0-4cf7-8e41-498a1de46a1f': 371,
 '345cbf61-5651-42ed-8c9f-7366fe42e644': 372,
 '1d613744-5f35-4ed3-9f16-313b50304730': 373,
 '02aae3f7-45d5-48d7-beef-679e373ef74d': 374,
 '1711a221-ca62-4626-a34c-9cc0616e8a08': 375,
 'bc788d27-7d56-42ec-8b87-131a5e7691f4': 376,
 '165a2320-9850-4a80-845b-1b1fcbc1143d': 377,
 '187597ea-1b8c-4f1f-afe7-dc93330b7375': 378,
 '05871bf9-78c5-48b8-81e3-e57f6b7ceb4b': 379,
 '713dfe36-2f38-48a1-b084-93b4b0b2f6e6': 380,
 '14242a9b-7eac-4188-91bd-6ccda1606069': 381,
 '8ee012ea-1b37-49f7-b3c2-1a96d35b7700': 382,
 'dd61f961-d23d-4d11-942c-1d249029bab4': 383,
 'e75f6138-2d55-462d-b2c8-a2b1feab5d29': 384,
 '16fb0d0a-08cd-40ae-897f-ef3b0801b4b4': 385,
 '6328ca85-5446-4a45-b70a-4fc454d559a6': 386,
 'a21b3637-40c7-44df-ba74-b3520d1fb483': 387,
 'fd5ea22b-04f6-4eb3-aae4-8bed17ab4f74': 388,
 '3bf6ac29-5805-463b-a130-672772aabd3e': 389,
 'fe404dd0-8b0b-4b4b-9b79-4b534c96be9a': 390,
 '9ec0889a-0024-4612-9d6a-6e13a582ec86': 391,
 '49c25c49-83e3-4197-86b1-1bfba9172c31': 392,
 '1b505d42-9ec3-423f-a36a-d19384bfdd70': 393,
 'ed657e81-e2c3-4fb6-a3e1-434d0aa93043': 394,
 'c4feb8a1-bcf4-4311-8ba5-7611f0cd3e68': 395,
 '60dd08b9-83a2-4f94-b84d-00153b60a6e5': 396,
 '55de1644-8c2e-42c5-b3fd-a836fbe25c76': 397,
 '32598e1f-f1a5-4515-9d58-a83e22993883': 398,
 '97cf07fd-e0c2-4275-a5bf-920e991a1acf': 399,
 '1fd940a1-7dcf-4ba6-8cc3-0a8a4e680646': 400,
 '48660996-2564-4d43-9045-b21b8aa0f1d1': 401,
 'b7ddf099-e2b7-4ec6-91ee-dbd5767d6c30': 402,
 '02cd0a09-fa65-4def-ba3a-dd3e25adeea5': 403,
 'e444f895-8a10-4552-9fd9-b562053a5140': 405,
 '4bc86846-8d1e-4b93-a566-d2ff5f3581b8': 406,
 'd85222c0-8ac0-4fa6-954e-736c369ff4a7': 407,
 '5862e904-5b24-4db7-a3a3-ea645b5e6a28': 408,
 '6481aa14-c69b-4f1c-b731-b74026dff35b': 409,
 '8e5a47d2-3dc8-48d6-8eef-feacd0f1c3b4': 410,
 '08941745-4443-4747-831c-770689c5c2f1': 411,
 '6db999c6-1e65-4881-bad6-64b856d92124': 412,
 '2bc28b49-2bd0-45c5-8f2d-3b2b9627011e': 413,
 '998ef516-6001-4f33-a991-60712de6bacb': 414,
 '1a77d6ac-35d1-49e2-8cc9-ed08eac67bb2': 419,
 'cb47095b-8c85-41e4-9627-b5db8b492406': 416,
 '54c59175-c1db-49d4-a530-f7e8c1447d93': 417,
 '54bd1d85-1f07-4f11-b950-66f1e28441f9': 418,
 '044f53d1-daee-4c83-9ab1-e13b89f237b6': 420,
 '06af5995-d58e-417b-a0fc-f7ddab4fb0d0': 421,
 'a8404b1d-4a9d-4dcd-915e-b9bfabe8fcb8': 422,
 '814873cf-03f8-44f0-a7fc-28b6582d84d2': 426,
 '19ecbbc0-dc28-4523-a1d9-4f157a6cfb20': 424,
 'd1f06b56-6eac-4335-a191-12b7356c83c2': 425,
 'ab21f917-a245-4408-9dec-714cbd528a78': 427,
 '9dae3fb4-1afd-4c6e-a331-1377b82e3bac': 428,
 'd8796e6f-5881-4457-a848-f04199e68e42': 429,
 '5c3b3295-7801-4bd7-a0f5-8b02e2f8137f': 430,
 '1a781640-c91e-4f1d-b4b2-4b62239a1330': 431,
 '9cdbadc2-a394-42f3-987d-62d7f399bd03': 432,
 '13f400a0-8257-42e4-9e2c-444bfbaabb61': 433,
 '68ba1038-c51b-4fba-b6f7-8650d62769f7': 434,
 '634c61f1-c46f-4e7f-b5fe-284954e1363d': 435,
 'ed3afeff-c766-4333-ab3c-47248aaa7296': 436,
 '856270e9-6d39-4b4d-bfa2-2cc8542caf96': 437,
 '78a203a6-8e35-4292-8f99-ec553b5c2416': 438,
 '9c7d3aed-a55f-4918-aa0c-c5a67d887657': 439,
 '0e033980-a52d-409a-90c4-ef03feb9fc2d': 440,
 'f67cd6bc-d1bd-45f8-809d-86dbcecdf05b': 441,
 '67b62a06-cb79-488e-8e1a-0c11ac92e702': 442,
 '04cf072b-79c3-40cf-8435-ae3f747aa0a3': 443,
 'bf289f15-abe1-4711-a83b-84a432707645': 444,
 'bfb37fa8-154d-4a11-9f2a-70b4a461ab26': 445,
 'f9167070-5be3-41ac-a0c0-e3a65e0684f9': 446,
 '5639955e-1e6b-4be7-845f-a3db74fb4db9': 447,
 '40f9ae27-106d-4731-8c0e-4913407845f3': 448,
 '0f23a243-03cd-45c6-bd7e-7250f23be7bb': 451,
 'dec3a040-c4b3-4e47-ab95-c5f4b43cd828': 450,
 'd6e3fc35-6dd5-4010-94eb-57eb5894b523': 452,
 'c97dd077-2426-4b8f-a899-d5835a1a369f': 453,
 'f7af9093-cddf-4d00-850d-d6d2c74229bc': 454,
 'dda06dee-1e31-4374-974f-99edf9c490db': 455,
 '71b0d0ff-9967-447e-9eba-a95fe06fe65a': 456,
 '4acbfb3e-06ea-40ad-ab57-71610425b637': 457,
 '2c2ff0b2-63e2-44d9-9c8c-659af9e7bfc1': 458,
 '1617809b-9518-4d57-8cc4-04e08eee3313': 459,
 '3d0fb74a-d6f9-4ade-b7db-272ad8a95b30': 460,
 '79094262-f336-4b31-9107-279cbaa9aae7': 461,
 '44f8b971-ae5f-4b3d-95e9-7f7a5f6a3834': 462,
 'c8cc4f18-05ee-4458-9d1c-9a418b0fa8d0': 463,
 'e600723a-6a16-46fa-a90e-782c99773143': 467,
 '7e99a807-33d1-4f37-8361-824393f823e2': 465,
 '6220c8a8-86ed-4b2f-8d03-0e8904644bdf': 466,
 '5fc5f31f-9b46-48ce-a758-70d628c0252c': 468,
 '36271114-8ea6-497f-863e-b859db6dfc1f': 469,
 '802bb4f4-2146-4ed3-8ec7-74b21af132ba': 470,

In [41]:
idx_category = user_id['629a0485-36c9-4a80-9f02-4a96382c3059']
sim_scores = [(i, c) for i, c in enumerate(cosine_matrix[idx_category]) if i != idx_category] # 자기 자신을 제외한 유저들의 유사도 및 인덱스를 추출 
sim_scores = sorted(sim_scores, key = lambda x: x[1], reverse=True) # 유사도가 높은 순서대로 정렬 
sim_scores[0:5] # 상위 10개의 인덱스와 유사도를 추출

[(3212, 0.191554480946969),
 (536, 0.17333571871089953),
 (377, 0.17227939898059863),
 (4214, 0.17227939898059863),
 (0, 0.0)]

In [42]:
com_once_user.loc[com_once_user['user_session'] == '629a0485-36c9-4a80-9f02-4a96382c3059']

,category_code,brand,price,user_id,user_session
1,computers.components.hdd,kingston,66.67,523117953,629a0485-36c9-4a80-9f02-4a96382c3059

In [43]:
com_once_user.iloc[[3312]]

,category_code,brand,price,user_id,user_session
3387,computers.notebook,asus,424.7,521542628,30e9ecd1-8a68-4cb3-88cb-debff0f17a3d

In [46]:
com_once_user.iloc[[536]]

,category_code,brand,price,user_id,user_session
549,computers.notebook,hp,320.35,551478118,9c664cb4-9311-4a80-bd17-fca008e49c98

In [47]:
com_once_user.iloc[[377]]

,category_code,brand,price,user_id,user_session
388,computers.components.hdd,transcend,45.05,548837228,165a2320-9850-4a80-845b-1b1fcbc1143d

In [48]:
com_once_user.iloc[[4214]]

,category_code,brand,price,user_id,user_session
4309,computers.notebook,asus,540.53,559683462,70d3de0c-ce16-4a80-b6b0-e69b3393af9a

### appliances 제품간 추천

In [5]:
appli_once = RFM_without_view.loc[(RFM_without_view['Frequency'] < 2) & (RFM_without_view['event_type'] == 'purchase') & (RFM_without_view['main_category'] == 'appliances')]

In [6]:
appli_once.drop(columns=['event_type','user_id','main_category','Frequency', 'RFM_label'], inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [7]:
appli_once = appli_once.reset_index(drop=True)

In [8]:
appli_once.head()

,category_code,brand,price,user_session,subcategory
0,appliances.environment.air_heater,oasis,28.03,b67cdbcb-b073-4271-b365-803c6fce53b0,air_heater
1,appliances.kitchen.meat_grinder,philips,120.95,94b897fc-80c6-492c-a456-707398c7cc8e,meat_grinder
2,appliances.kitchen.washer,lg,308.65,5e227e58-6117-419c-b45d-ac54be44716d,washer
3,appliances.kitchen.refrigerators,NaN,204.33,788ec8fe-f198-4484-b911-ba5841c55c68,refrigerators
4,appliances.personal.hair_cutter,moser,47.88,35323009-6410-4412-930e-e7855384a5da,hair_cutter

In [9]:
appli_once.shape

(31936, 5)

In [50]:
tfidf = TfidfVectorizer()

# Fit 후 dtm을 만듭니다.(문서, 단어마다 tf-idf 값을 계산합니다)
dtm_appli = tfidf.fit_transform(appli_once['category_code'])

In [33]:
dtm_appli_df= pd.DataFrame(dtm_appli.todense(), columns=tfidf.get_feature_names_out())
dtm_appli_df

,air_conditioner,air_heater,appliances,blender,coffee_grinder,coffee_machine,dishwasher,environment,fan,grill,...,oven,personal,refrigerators,scales,sewing_machine,steam_cooker,toster,vacuum,washer,water_heater
0,0.0,0.862929,0.196043,0.0,0.0,0.0,0.0,0.465747,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0
1,0.0,0.000000,0.210327,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0
2,0.0,0.000000,0.317425,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.82639,0.0
3,0.0,0.000000,0.293136,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.85416,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0
4,0.0,0.000000,0.145957,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.631627,0.00000,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31931,0.0,0.000000,0.185239,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0
31932,0.0,0.000000,0.317425,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.82639,0.0
31933,0.0,0.000000,0.226555,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.00000,0.0
31934,0.0,0.000000,0.212498,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.977161,0.0,0.0,0.0,0.00000,0.0
31935,0.0,0.000000,0.317425,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.00000,0.0,0.000000,0.0,0.0,0.0,0.82639,0.0

In [51]:
cosine_matrix = cosine_similarity(dtm_appli, dtm_appli)

In [52]:
np.round(cosine_matrix, 4)

array([[1.    , 0.0412, 0.0622, ..., 0.0444, 0.0417, 0.0622],
       [0.0412, 1.    , 0.2101, ..., 0.15  , 0.0447, 0.2101],
       [0.0622, 0.2101, 1.    , ..., 0.2263, 0.0675, 1.    ],
       ...,
       [0.0444, 0.15  , 0.2263, ..., 1.    , 0.0481, 0.2263],
       [0.0417, 0.0447, 0.0675, ..., 0.0481, 1.    , 0.0675],
       [0.0622, 0.2101, 1.    , ..., 0.2263, 0.0675, 1.    ]])

In [64]:
category = {}
for i, c in enumerate(appli_once['subcategory']): 
  category[i] = c

category_id = {}
for i, c in category.items():
  category_id[c] = i

In [74]:
idx = category_id['air_heater']
sim_scores = [(i, c) for i, c in enumerate(cosine_matrix[idx]) if i != idx] # 자기 자신을 제외한 유저들의 유사도 및 인덱스를 추출 
sim_scores = sorted(sim_scores, key = lambda x: x[1], reverse=True) # 유사도가 높은 순서대로 정렬 
sim_scores[0:5] # 상위 5개의 인덱스와 유사도를 추출

[(0, 1.0), (30, 1.0), (47, 1.0), (58, 1.0), (63, 1.0)]

In [80]:
appli_once.iloc[[967]]

,category_code,brand,price,user_session,subcategory
967,appliances.environment.air_heater,tefal,167.29,f9b77efc-e1f4-44f7-a30c-de1176c6689c,air_heater

In [81]:
appli_once.iloc[[0]]

,category_code,brand,price,user_session,subcategory
0,appliances.environment.air_heater,oasis,28.03,b67cdbcb-b073-4271-b365-803c6fce53b0,air_heater

In [82]:
appli_once.iloc[[47]]

,category_code,brand,price,user_session,subcategory
47,appliances.environment.air_heater,NaN,10.17,4f885f6f-df02-40a1-b640-bd6c44861709,air_heater

In [83]:
appli_once.iloc[[58]]

,category_code,brand,price,user_session,subcategory
58,appliances.environment.air_heater,midea,47.62,f7e2c109-b4d3-4614-bdc3-3afcdd3f4937,air_heater

In [84]:
appli_once.iloc[[63]]

,category_code,brand,price,user_session,subcategory
63,appliances.environment.air_heater,elenberg,33.44,cd592886-cf59-4d47-81a3-3a26f1605306,air_heater

### appliances 유저간 추천

In [9]:
tfidf = TfidfVectorizer()

# Fit 후 dtm을 만듭니다.(문서, 단어마다 tf-idf 값을 계산합니다)
dtm_appli_user = tfidf.fit_transform(appli_once['user_session'])

In [ ]:
dtm_appli_user_df= pd.DataFrame(dtm_appli_user.todense(), columns=tfidf.get_feature_names_out())
dtm_appli_user_df

In [10]:
cosine_matrix = cosine_similarity(dtm_appli_user, dtm_appli_user)

In [11]:
np.round(cosine_matrix, 4)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [12]:
user = {}
for i, c in enumerate(appli_once['user_session']): 
  user[i] = c

id = {}
for i, c in user.items():
  id[c] = i

In [13]:
id

{'b67cdbcb-b073-4271-b365-803c6fce53b0': 0,
 '94b897fc-80c6-492c-a456-707398c7cc8e': 1,
 '5e227e58-6117-419c-b45d-ac54be44716d': 2,
 '788ec8fe-f198-4484-b911-ba5841c55c68': 3,
 '35323009-6410-4412-930e-e7855384a5da': 4,
 'd244ccce-4dbb-4ae6-af48-98eb36069e19': 5,
 '87f507c9-8679-4b25-87f0-dc90e36b7b6d': 6,
 '09da2c0e-55cf-4017-99eb-2fb64f550404': 7,
 '6f7b28d9-676c-4840-945a-184bbf955181': 8,
 '0b58cee9-ab6f-452a-8b17-e2239707e299': 9,
 '87515b74-457c-4272-8fcf-5739f0196b4e': 10,
 '62c80e92-1f6c-43c2-8e28-87a3cf7a9243': 11,
 'ddebe7b1-5376-49e9-8e87-14b575a30174': 12,
 'd36a86cc-b609-4b78-8040-389d39fd35b2': 13,
 'c62afcb5-b721-4a46-88ca-2c7f9ee42f07': 14,
 '9bcee4ed-01fa-468d-906b-565bc222fa21': 15,
 'dc03489d-7086-4282-b4d0-bd7aee07d491': 16,
 'a3466904-e855-40c5-b3bd-6739e29ea603': 17,
 'ae16d5ad-53d5-4f4b-9d79-4d32ab99641e': 18,
 'c7b658a0-ffec-4e5a-9c39-05193809de53': 19,
 '52a857d6-b4db-42cb-bf03-b0b66cd36c72': 20,
 'df26d914-fe85-440b-86be-15d6de9115a6': 21,
 '7f24153b-a9ad-4274-8f99-a0b8fe9940e5': 22,
 'a1548ed3-1187-4f52-b547-4da26e76be00': 23,
 'a70a2cab-e017-4d0e-a328-d04274908fd4': 24,
 'f9085968-9002-4caa-a80e-e796816beaaa': 25,
 '85b01a68-3442-498a-8db7-1ad53bc0ad34': 26,
 'ee3bfc89-3b9f-42dc-9eac-67c37de3cc55': 27,
 'e3a10c85-52c3-41e2-99e8-76c83d96c8bd': 28,
 '23616354-7b1a-4cff-aeb9-b37be98d0c6c': 29,
 '8e5780e1-cdc8-4d51-86f7-5bc9b8aa3b40': 30,
 '12152add-9e11-4295-8b9f-eee6b5323196': 31,
 '49470c03-66d9-4770-b523-abfb387d5b7a': 32,
 '43282a03-8915-4d2d-9506-c69bfc95adb5': 33,
 '2e18f7e3-b3d5-4b9e-b6ac-36de0c3ca8c0': 34,
 'da158c7b-a363-44a3-9604-c710ab2b15af': 35,
 '8044b355-90d0-4c04-b08a-f713d3cf8ea7': 36,
 '629591a5-469a-4e7d-a0a9-2d89c29968cb': 37,
 '2bd2e19c-3e8a-4bbc-bac5-d7e989ede1a6': 38,
 '3ca894d8-510a-484a-93e1-0dd557255695': 39,
 '20194b52-cf28-4be3-9fb8-c6ca112d5265': 40,
 '8e0b2a86-7d8f-4e20-bcb0-4f5b7ce37ce7': 41,
 '027aaf7f-ad8a-4552-b2e8-b7bd0fea27c4': 42,
 '592ad7fd-8292-4fcf-bf79-0e30bae9119d': 43,
 '2aae3558-a992-426e-8fa6-e4a77c63d129': 44,
 'dd129090-e109-4423-a4d2-c2e477b876a4': 45,
 '8c523672-f633-4e8d-9a4d-16a2d04dfcb4': 46,
 '4f885f6f-df02-40a1-b640-bd6c44861709': 47,
 'dd44abc3-18ff-4d58-af2a-f09efe0ed57d': 48,
 '27bd9dcd-5131-44ed-937d-343323fcc6f4': 49,
 '07fbd9b3-b736-4179-8377-8af48510aaa1': 50,
 '784238a0-da01-4c34-9034-d0e9dc06b2b7': 51,
 '585119f4-7f24-4a9a-89ab-c74e0f9a1b4c': 52,
 '7ca3d8d1-ab9f-42d6-9003-395bfb7e29b4': 53,
 '41e13206-7783-4cea-9b6a-e11908c0860b': 54,
 '33976747-7e52-46e1-afd7-26b7168a0987': 55,
 'ec0a7290-22b3-4d45-bcc3-f362d1007f3f': 56,
 '922f2282-65c6-4545-9a7c-bff14be0d2fd': 57,
 'f7e2c109-b4d3-4614-bdc3-3afcdd3f4937': 58,
 '2ed8a59f-c551-4ca2-86de-8712345fc920': 59,
 '5cedb77d-becb-474a-9612-ccbda5361f8a': 60,
 '0c8177e3-e3a8-40e8-a225-bf6f17612042': 61,
 'f49bf9dc-5f9b-4d54-a1e2-84097e9405d4': 62,
 'cd592886-cf59-4d47-81a3-3a26f1605306': 63,
 '58da0a33-f999-481b-9239-fca79698d3ae': 64,
 '54243b1c-14aa-4c29-9ddd-6607865700a1': 65,
 '5e4588cd-2b82-4a56-a0a9-5c82b06bb20d': 66,
 '9d089b49-3450-40da-8249-2d63745d61cf': 67,
 '36730e1e-c49a-4c3a-9320-aaf2fa8d3ba7': 68,
 'b5b4f501-c02a-49cf-ba7b-790ace4a7b34': 69,
 'cd598a8a-aa1c-4953-bf03-bd39d9cf2221': 70,
 'f546e6bf-3eca-4380-af94-886c7ce7ac7f': 90,
 '01ca00ff-1fc1-40ba-ae4e-b7398dfe8636': 72,
 'f64e6751-9f5e-449d-8ffb-bc2065d07271': 79,
 'e4880436-7f5d-4256-9a01-380f7cb67f2b': 74,
 '066ded29-5c3b-4bca-a3ce-7d3434503213': 75,
 '012c798a-a30c-4a7a-bbad-c9e3e8f5a5db': 76,
 'bd62c57d-0196-4268-950e-10ed87053fe7': 77,
 'b7360dbb-427a-428b-a4fb-1f8872884d4d': 78,
 '9d49014e-da07-4cef-826a-00cb0859c2c1': 80,
 '52033edf-db58-44e3-82ab-6d267155135b': 87,
 'ea5c48a4-f032-4aeb-bc3c-9ece49ac3ec0': 82,
 'd5297c7a-5dde-487e-b192-a1be39c37c58': 83,
 '3b719a5b-018b-4b1a-9d2d-fc9cdcc8bb51': 84,
 'e309852b-fa89-48b6-80b8-224601c13359': 86,
 '2450df77-8b8a-4ac4-9316-34782fbba1a7': 88,
 '9eb6745d-ee8d-4bab-bade-a60f5b3ac13c': 89,
 'b8bc72ef-1c93-4bcb-85a5-db3fc962b025': 91,
 '455f3aa3-df7b-4426-8015-717e8d094463': 92,
 '79943db8-aa35-4197-a3e6-4d545a0a6585': 93,
 'c397b006-1157-4db1-a8b3-07e58c835bf4': 94,
 'e214f24c-595d-4fe3-9b5a-7e679e1c7238': 95,
 '8379876f-52c0-445d-8052-c54dab070cc8': 96,
 'c4f2584e-1b94-4b3b-9fe9-3ad7571a6efa': 97,
 '2772240e-5905-4ae0-a682-2cdb50624952': 98,
 'fd66a737-84d6-4ca4-a2b5-85752270315f': 99,
 '77fb1a1c-8caf-4b7f-ab44-fb3cd273dd0e': 100,
 '9db04b9e-16f1-493e-9e22-a2151d23e949': 101,
 'abc1b60a-2c67-4f46-b124-8b64ed7d9e1b': 102,
 'cd6dcd87-5adb-47aa-8ecd-9149644c6efb': 103,
 '83f2ae21-e31d-4d71-8fd0-953641768424': 104,
 '4ea6b06e-bfc1-4021-8132-c0d1cc470ade': 105,
 '2d878ab2-e398-422d-9063-6426548643aa': 106,
 'd4ab910e-5586-480d-b038-9fc2cb61ba0c': 107,
 '4f5a9325-1bd3-4c4b-9286-944aba1389da': 108,
 'f3e42164-666c-43a5-a0d8-8871aedb9d31': 109,
 'a06fe1f5-ae85-4071-b927-4e9f59cfb0eb': 110,
 'd1172bd3-9b54-4cd7-b202-d5012c3903b8': 111,
 '7ec117af-5159-4545-91ff-b4686981b7ae': 112,
 'af86d4d9-bf2b-4178-b0e6-1427d78cd5c7': 113,
 'da8b4594-e52f-446b-984b-2e8b68dd984e': 114,
 '3d57b23e-c071-4f84-a179-29b825d21aed': 119,
 '49ef4f15-2533-4af5-9a64-c129284ef4c0': 116,
 'e455d872-5182-4d00-bad4-3a4f6e545c22': 117,
 '6472bd61-ed17-4703-9eb3-36710c87f561': 118,
 'd4047c96-7a41-44b2-bfae-3318eac13418': 120,
 '49fe2d8a-7b85-4f1f-ad0c-91757e8a259f': 121,
 '3ba7bd55-606d-42e6-8bda-fda4dadea6a1': 122,
 '8c66daff-a156-4629-afb6-47ae274f22bc': 123,
 '1c12f1a6-dc77-4ac6-98b4-2656612dea8f': 124,
 '25b07401-1b79-45c6-b856-eecc018afb55': 125,
 'c1e452a1-2fa8-4d18-8a35-fbb73d4810c0': 126,
 '8a75d79e-26d9-46d1-b24c-835b6f0f656c': 127,
 'c46e9147-fbb1-4a4c-98ac-34383e6722ca': 128,
 '0c929ed5-57d9-4d10-8c6d-b050d90fdb9c': 129,
 'db7a668f-f621-4606-af31-b563a4760ed6': 130,
 '26f24e9a-4318-4960-9897-173dc5cad6a6': 131,
 'dd7c58ca-ee7e-49cc-bb7b-69910d89699f': 132,
 '4f5230ee-b5a5-4d70-903f-9f4fd6adfc4b': 133,
 '64080575-f530-4ef3-8621-5b129a8bf7f9': 134,
 'a365702c-765e-407c-b558-3cfabbe14755': 135,
 '2a196320-ca51-4c74-8873-ad55daa39de3': 136,
 '748e33f5-a0be-485f-9231-4f3352e6a65c': 137,
 'fafbeb7e-6a03-41b1-8311-854ef9c4d40e': 141,
 '735332b1-6aa9-4d41-a8a4-e638f2945420': 139,
 '12cc70e4-eec0-4690-a566-6f4b5c49d631': 140,
 '1fb40a5d-f9ea-4c0d-b661-c74ce2b351ba': 142,
 '872cff6d-1fde-469c-9026-bc1dcb704d5c': 143,
 '24b99183-97bb-4eeb-8ee9-8eae466317f7': 144,
 '42848801-1cb9-4702-8492-31a39c48af7e': 145,
 '52545153-e37e-4903-a4dc-d205d693c114': 146,
 'cb55b0e4-7e35-4e46-9ad1-797988f4b53d': 147,
 '2696be8f-5cf8-414d-813a-f8f52e0cc2e8': 148,
 '11222827-0fcc-439a-ad76-7b99a1ba85d8': 149,
 'ec48d798-a0f7-4e67-8565-6c7f14e4631c': 150,
 'eaebc353-7b4d-48df-b4db-19ba15e61945': 151,
 '9867d446-5b86-486e-b9f6-af21a9f9bcc4': 152,
 '698c9118-b3d8-4f55-afda-274b9d3777fa': 153,
 '1a934b87-a2bd-4e36-b662-d12bee14a4c0': 154,
 'fd397a3d-be86-4a00-899a-575724c975af': 155,
 '816c9822-1dd9-43c8-911f-f03dd50d0e5e': 156,
 '92e636da-6cbd-479a-850a-ad24948fa94e': 157,
 '5cbb13ba-7099-49d3-8c8d-37a1a19362d7': 158,
 'd310b3dc-b4cf-4a6f-9179-e4712ed01033': 159,
 '192e9ba9-8baf-4e64-b395-716a7951b5ec': 160,
 'aa5decd5-7dc3-4c2f-b32a-f673ae7368e6': 161,
 '9cf284d8-60ac-415d-be3e-4319a202c162': 162,
 'ded646fc-bd81-4f7a-a571-7b884176cdb1': 163,
 'e5ada616-a5e5-4c39-ab67-851b0a998a20': 164,
 '6940ef94-2f16-487b-9e37-00c77c3012f5': 165,
 '04fbabd6-4832-4539-9317-f85ffab4e9a8': 166,
 'ec8fd8c4-f1f1-4cc1-83ad-d3dc4f4096c1': 167,
 'c2b4312d-5b4a-4935-bf8b-882d32f544d1': 168,
 'c1b71a4f-d57b-4d40-9694-868362449da4': 169,
 '7ba3ff6e-462f-461e-99fd-ef20b3996ce7': 170,
 'fd738abf-593a-4a0e-b4be-24ea9d770b0a': 171,
 '491e9cee-0303-49d2-8ba1-64b61e4d37d0': 181,
 'f4bb544c-857c-49d1-9d11-0d544464e061': 173,
 '25f653af-bcef-494e-a012-53c40c1b7f06': 174,
 '221bb169-937c-4a71-8448-222bbf1690ba': 175,
 'b3a535ed-166a-41b0-9e6e-01ae521a8b44': 176,
 '778d3fdd-6564-4e8c-ac7f-7318cfc5bbb8': 177,
 'af8ad5b7-b437-4b29-bbdb-f46921dc8409': 178,
 'bbb1770c-6288-4864-8d6d-16f7c0ad1096': 179,
 'd8ba60f6-a669-4a25-b4b4-9a24922e8491': 180,
 '017b3392-d434-45fe-bd90-c7ae588f5904': 182,
 'f9f4c76d-9ce5-46b1-b187-586ae1e01877': 183,
 'ec9a328d-1252-43dd-a41a-95c87abaf519': 184,
 '641ae779-d086-4903-bea1-12280014296d': 185,
 'a10f1e3f-010e-4021-a05a-b544fce78857': 186,
 '1a5c6d20-8201-4ac4-bdc8-5fbf41a376cb': 187,
 '2a8f3639-e3fa-c6ac-72d2-8280eaebed2b': 188,
 'dbf8c58e-487e-434f-9369-78cfc3469ac5': 189,
 '6a12d39b-43bf-47b6-9f15-ec34b7266290': 190,
 '54364cf9-1569-4c64-95d0-bfe93df4f5c0': 191,
 'ac0d5881-d9ee-4303-9ed5-bd790aa3be79': 192,
 'b0db5ac5-c56c-468a-b7cd-6144d66f2de9': 193,
 '0a069320-5ce3-4e57-bb3c-80736bec7f37': 194,
 '276548f0-b0bf-4535-895b-b4ce4b004fff': 195,
 '01b98b9a-bde6-4483-a3e2-51408abaa37c': 196,
 'bfd24b48-d546-48d3-8338-c3ba78863931': 197,
 'b634f0aa-40e3-40e0-8ba9-3bee285758f4': 198,
 'd771fde5-dfd0-4287-91c3-aa2644202b75': 199,
 'db753106-77f3-447b-95bc-9a43927bb7b8': 200,
 'b6584f8f-ded9-4a70-b97c-99fa9d169b9a': 201,
 '27274186-dc9b-47f2-9f1e-e4b431536af3': 210,
 '3b74c7be-b4a8-452e-9c5f-2777c384c154': 203,
 'd7d3953d-ef76-4f9d-8a18-93fe2ab2ee25': 204,
 'af57e472-14cc-4a99-898e-e5c14206f3d5': 205,
 'f529413d-a598-4905-a701-663941cee3f9': 206,
 'a18a415a-fc5c-466a-a2bd-0f5219c1d9d8': 213,
 'c3c280cd-76cc-42b9-bcda-92c2005111d1': 208,
 '03021548-af9a-4e2e-8661-7c849c3ccf70': 209,
 '0a7e9490-2780-4199-94c1-8e5543d2f39b': 211,
 '44025a49-634a-43c6-a193-76778c44cf35': 212,
 '5afe0d4d-9c8a-43b1-8e8e-c4cfd3bd2240': 214,
 'a0d4759c-325d-4c48-9423-3f1949153ed1': 215,
 '1324dcf5-f544-49ec-8eec-379348cc98fb': 216,
 '012f8a3c-2a88-475b-ba1d-e12e5cc1afd0': 217,
 '1a29e4d8-151d-49f4-ba99-53f3d9b7f6cf': 218,
 '2f753f79-cac0-4273-9401-e13258c0f239': 219,
 'a3a8eed9-2a32-44b1-bee6-c8330117be42': 220,
 '8a76ce9f-3d74-46e2-9914-7c887b4519a7': 221,
 'aaf6263c-7920-41db-b38a-aace80e16811': 222,
 '2615f471-dc60-4430-9b7c-98d140536c46': 223,
 '1952a8ab-4ecd-4a69-8ef0-7f155dee5cfa': 224,
 '8846380d-8531-4178-b03c-93fb50836282': 225,
 '48fc477c-2676-43b5-b273-362c175d220e': 226,
 '99187d07-45df-4a6e-a281-fd05c4824ec6': 227,
 'd1db4725-f434-4be6-a2ab-511d23c99a38': 228,
 '5a34f9b8-1c9a-09b0-97d8-0895df2aa5dd': 229,
 'c9aa1bae-94f9-4e55-ba1d-afb95214fb46': 230,
 '413cec43-f57d-418d-8906-fe8b1dd0fcdc': 231,
 'a97dcde8-58cd-4971-b060-d57686f46390': 232,
 'a791d7dc-d2a8-412d-bf61-a8495dcb9b8f': 233,
 'b77f971d-7168-4793-847d-08fcd4d769d1': 234,
 'b587eecd-ecb7-41f8-856d-5ee94f5dbda7': 235,
 '0de150d4-8fb9-46db-88ee-72ceb9b67343': 236,
 '4a570095-c35a-471e-9f00-e55825b18cc0': 237,
 '7fc34cb5-8a94-4208-bc1c-7d535ccad1c9': 238,
 'ec803b1a-5399-4a21-a5ca-7bb3a9ee05d6': 239,
 'f87d3a52-c361-4ce4-b187-9b52fe422850': 240,
 'ea86f63c-b170-4aa4-a758-0586b16726a3': 241,
 'd2676295-09a0-42f7-9eeb-c5431ace7088': 242,
 '3edbba30-d2d2-4b56-a444-32ee09eb1b44': 243,
 '9e4e43bc-c051-4cdc-948f-eba40d77bd68': 244,
 'a27adf85-85fc-41cb-919b-5656e22d1631': 245,
 '09ce1d13-be5b-4316-9861-bfeb8651b632': 246,
 'c4c2b8a9-1588-46da-96b9-009cb4949b80': 247,
 '3c4f2fa8-f349-4f8d-be45-a03be58711cc': 248,
 '6ee1592b-a912-4e39-b060-a35ebe4b8e20': 249,
 '1293bb6a-fac6-4c84-92de-a49be4262e5e': 250,
 '03c61b0d-01e8-4c22-8201-8b8ed01111b5': 251,
 'ea598e0c-6e1a-4a9d-95ba-4e6a88e8bc8d': 252,
 '249aed6d-7083-4720-b70b-163d61d4ccae': 253,
 'ba02d0ef-bf7e-4fd0-9c10-d69ae0164a78': 254,
 'a9279da8-9340-4688-ba93-97fad53200fd': 255,
 '96f3dedd-5f28-4b91-92eb-4ce9021b6dc0': 256,
 '6d4df6c7-cb55-4d6d-a486-27c9c6313ea0': 257,
 '6f1f6860-443b-4256-9ec3-ea80b89ee581': 258,
 '9a39c2b8-4011-4f7f-b0af-e8592631f2b5': 259,
 'c4e24c05-83c5-4ce6-b139-dd0473df75e0': 264,
 '0fde283a-70ed-461d-8e92-1785f47826c2': 261,
 '4af9fa1e-053d-4783-b255-d1aad2b5fad2': 262,
 '08a3bd64-379f-479c-8a61-b0d694593564': 282,
 'd6a3071b-d675-4f9c-9000-3a6ccab08e49': 265,
 '63cea9ff-853e-43e7-837e-f929fcfb1de7': 266,
 'c688d2f7-623a-44c1-af73-b1e832ad1763': 267,
 '6981b0e0-eceb-4050-85a2-69179637bbe3': 268,
 '6b6ce785-df8c-4365-b5cc-8a0b2c55678f': 269,
 '34c34d98-8bd0-49a3-9753-fd58485f40f9': 270,
 '455895c5-ce3d-49ad-8c1c-8703f5075f3d': 271,
 '8ada3f32-75e6-4fdb-9083-cd64285e3535': 272,
 '28eed61a-4a88-4dcb-a744-1480fc750937': 273,
 'ef8258a4-432f-4c95-834c-880e21aae106': 274,
 '3aa8d079-898f-49cf-811d-d2cf0e7fcd39': 275,
 'f37fc1b2-6e36-4a86-9b0e-89e6a043ec34': 276,
 '082837f8-392a-4c20-97b8-81d282a827bf': 277,
 '9103010e-f69c-4181-9d2c-42334cb832bb': 278,
 'e4c5b358-09cb-4c5f-a951-2e86e3936f35': 279,
 'a5571e92-a83f-4f26-8ee1-00a7aa4b55c8': 280,
 '078f53e3-0e15-46b9-af17-fe518fcbd91c': 281,
 '6e36cb8b-7ab1-4722-8739-9cbe3ed3664b': 287,
 '9fc6f537-5936-44a6-a688-a2ae69766c5f': 290,
 '788046e0-07e9-4d40-ae7e-e16a147e177a': 285,
 'ade42ea3-9b60-49bf-91fe-86d81b951461': 288,
 '3580eb76-8ec0-4e7b-bb4d-3b85fc22abab': 289,
 '39956d47-49d9-422d-ae90-58afd47d1898': 291,
 'acb71ec8-287b-41a6-98c3-d2ecffb72e82': 292,
 'd1e46150-d813-4d7c-8450-0930ada0d4f7': 293,
 '2814bbf1-aa88-4d5d-ab51-554a39d5e828': 307,
 '5e3c6852-9dc9-47f5-a2b8-23507224bfd0': 295,
 '9a3ceb74-8c36-4181-a47c-ab0098836da9': 296,
 '7e597774-3a01-4d48-8dad-5f9b21849c5b': 297,
 '05277967-6b6e-47c2-877a-8b755f325ae5': 298,
 '5ab6570b-04d7-4a9b-9959-6c3fa8f3c082': 299,
 'c99374a2-fe71-44cd-ba55-380a1572bb22': 300,
 '2177451a-0e51-4607-aefa-8fefae8d839a': 301,
 '6380c540-6e1b-4c4a-a24d-3708eb4ff98b': 302,
 '641379f0-42a0-40bd-9775-a03bb67541c6': 303,
 '3a7cf18e-3b24-4ec1-ad72-c1bab9763105': 304,
 '03390a45-8f3b-4241-9f0f-179713b729c1': 305,
 '3c362a56-9ef0-4dd2-8a25-bde977be15e0': 306,
 '59c2b208-7919-424b-9577-ef9ae7298e8f': 308,
 '43a7a75e-7f17-4000-a183-61b0670dcb71': 309,
 'fc86ef32-d2fd-4162-98f0-d53af1f43b70': 310,
 '6bcf6d9b-8e37-4f21-88da-55de7da9c418': 311,
 'a57fd913-75d9-412e-bc4b-025b704baa0a': 319,
 '3fa1e92a-f806-4d86-abb9-7bc0606b8df4': 313,
 '4a974ac6-6212-4f01-8ceb-c34b772faa65': 314,
 'a1d58ae9-2763-4cc3-9a67-5230ea253aa4': 315,
 '9a6a3e7c-6696-43bf-bc30-7f059c8a719b': 316,
 'e763acff-dbb3-440d-bfcd-b27dc3952a63': 317,
 'cd3748b6-6afd-4097-8de4-1af166090358': 318,
 '17b17804-483e-43d8-80fb-9a7690d7eac1': 320,
 'fc16fb03-7015-42e3-a999-1fdf4919e2de': 321,
 'cbe29d84-8133-4ff9-9516-9dcb40546b45': 328,
 '4af3cea0-f09d-4ef2-96ff-2adca73aa8ce': 325,
 'e9ee7d08-a498-4c26-902c-7d3a4cab61f7': 324,
 '9c55c653-6860-4364-bf82-1f6d32a65299': 326,
 '74daa415-6d65-42a5-96cc-343ef802fe1c': 327,
 '50ae901d-72f4-475b-8d6c-30cdaebcd3ac': 329,
 'afab469e-6fc4-45e3-a3e2-47e378a7837a': 330,
 'd1aa8cae-fea1-4e7f-bb53-1b086d1ae019': 331,
 '9a97ff10-a06f-4f89-829e-71c6bf5a65ce': 332,
 'bc5b2108-6395-82da-6ffa-b5ff854afc66': 333,
 '083ed112-7f51-4acc-860e-ed4039c2b443': 334,
 'f98c8d41-026a-4b7d-89bb-f9d80994b7bb': 335,
 '8ca3ba6e-b821-403b-a711-8551e8435d31': 336,
 '7743c43c-2b66-4478-a5d2-5dd0b3bf57f1': 337,
 '73bcd8df-bf24-43a0-8439-d733968cc858': 338,
 '706eda09-3476-4133-a712-efc441c7f37b': 339,
 'f1ce3ca8-422b-48cf-8475-0d6ae48c0e38': 340,
 '153b719a-52dc-4400-822e-f92a0fd9cdbc': 341,
 '4ae4ffcb-22ed-4f1c-91e3-2790608995c0': 342,
 '9c5d98b0-876e-476f-9c12-9c9410d027dd': 355,
 '4c3b0c02-425c-41c9-be42-d4cd7b7e859c': 344,
 'd4097034-9ff6-464d-91fb-3819207a9d69': 345,
 'a375ae4e-486f-4d00-9e1c-bafe1c861ddc': 346,
 'fb9143fb-54a1-46a7-9368-bb422f9b1812': 347,
 '49627ed0-d999-41bd-ab2c-485f0ffe714c': 348,
 '4fb9fe6b-cc70-4e7f-a0c0-418425cd97f7': 349,
 '57aa5cbc-8e5b-4b09-8a51-5b001e8ccf75': 350,
 '8461838f-1744-40c7-bed0-d741b4917e97': 351,
 '8fc58c57-dfff-401a-982d-e46224a33114': 352,
 '72102e05-d582-4c44-84ee-1e967343b3f0': 354,
 '21e99196-807d-4f96-8c71-54ab53d7c1af': 356,
 '4be4ec2b-a0f5-49c3-a71c-559206fee6bc': 361,
 'e7e1332c-ac79-405a-abde-faec8775a2d9': 358,
 '510318fa-e09c-4acf-bc25-9b7a6d9122c5': 367,
 'e589d71b-78bd-4bd6-a466-b7f3433d0376': 360,
 '71103879-bd68-473a-8cdd-66480a3121b3': 362,
 'e6b7e5fa-8f53-426e-b2f4-00a14a1a8bde': 363,
 'ad9cd6de-be76-42cb-81d3-d690cc0e058f': 364,
 'b3b4c293-eb86-4b86-a271-1f35ea4c0d05': 365,
 '2116fc8a-4a7c-4e71-98af-8aa1b6639331': 366,
 '7562eb1a-8a03-4f08-83c4-820c8272c996': 368,
 'a949b94d-b51b-4c8e-9449-8089d4d98708': 369,
 '0cf8a534-ea92-4206-9f16-828d14035b22': 370,
 'b19baaf2-b94d-4408-9c48-422c624c3139': 371,
 '2b6f57b0-96b5-4102-93b5-95ebd9be7470': 372,
 'cc7ac00b-99f9-4282-9731-a6ea0f20acf8': 373,
 'f1d726d4-27f4-4164-adbb-b0a7a903c2cc': 374,
 '346cd6e8-cf9c-40ec-a6ac-d26c8c7fe7e3': 375,
 '7e65e576-07da-469b-ba06-dd5e74a03499': 376,
 'b8ec5d2c-8d52-467c-a8cf-4ce06ceae392': 377,
 '299552be-895b-4b7c-812f-3831583a97d8': 378,
 '7d7c168d-05d0-4c1f-a197-23c95723d232': 379,
 '5461bbd8-bd93-475f-9541-5b1541fd44b2': 380,
 '72345f33-566d-4614-ac6f-aa9f4ff93926': 381,
 'f5067f83-ff93-4dac-b766-b1e130a6910f': 382,
 '1f165c99-2f48-4919-ba93-6ea5fbc6891c': 383,
 '1caece72-282c-4510-ba5d-39c6e1c2e9fa': 384,
 '439824e4-b918-4cdb-ae24-2c690eee4164': 385,
 '8be761a9-6c4f-437f-b76f-eede5ed37faa': 388,
 'a6128578-59a9-4ac2-b47c-6b688689c937': 387,
 '2e269ea6-4e6a-4b08-ba98-f14066e650b8': 389,
 '1287816a-ad16-4126-8fff-24403d6b54e1': 390,
 '837e4f3c-ab82-4eba-9638-40f7055d6e65': 391,
 'f2cd5e56-632e-4a90-8fa2-cb1e186c1877': 392,
 '20be4b8f-066d-49d2-9fba-e9a9359f9361': 393,
 'f027e53c-59ad-4a22-a622-7a188463768f': 394,
 '29db086d-6136-4b5a-baf2-10efc8509a7e': 395,
 '99dffc48-e419-4fce-89d4-36d045d3d739': 396,
 '4bb57eb9-1673-4775-a6f3-9fb9452e3632': 397,
 '5de3d619-10f6-4ef9-8913-e5b788da733d': 398,
 '612daf53-61df-4cf0-9eae-7a0cdce121e8': 399,
 '36ccbed8-2230-42d1-b68c-470a7e124a1d': 400,
 'f512d364-2b12-4f8e-8cd9-75ddee3d9e3b': 401,
 'b70b715b-28ac-4e5d-947c-215c71acd989': 402,
 'c88ccdb0-0ad9-4e46-bd76-8f8b66a883e6': 403,
 '6c46b951-e9d5-4cc5-93cd-92aa437d1e52': 404,
 'c2c90f54-4813-4e14-8b7f-0562016e00fa': 407,
 'af15db2a-38e1-4a15-9fee-1c06c2c0d912': 406,
 '69ba9fba-bf68-479d-9dbb-692737417e84': 408,
 '04145d9b-f80b-446c-a56d-517860508d4a': 409,
 'eab01eaf-d781-46f6-89cc-4c04bd35032c': 410,
 'fdc38f45-6e19-4f3c-a355-87beabb99930': 411,
 'a68312a8-fa06-4a3a-8ff5-6919a13c865e': 412,
 'f8f8c076-1d76-4115-9042-adbd437d7616': 413,
 'e4db38d9-0adc-42da-a941-2a645265762f': 414,
 '2f2988cc-7364-4e20-b0a2-201526193377': 415,
 'fa78fa65-22d6-4f64-be2a-77977d354c9e': 416,
 '66cc410f-53b5-4e97-8f83-8fc26915b373': 417,
 '27c02d95-cb77-4dd6-a48b-2982586d43b5': 418,
 'aad3eca1-2eb7-4003-9585-845b7448a870': 419,
 '15459ec7-7ce5-4794-817a-437498b3e4f5': 420,
 'ff8f3ef1-02d5-460b-83ea-ca171687fce9': 421,
 '387d47e6-72ca-4edf-9835-8b0f495780e0': 422,
 '73f1f935-77cb-4dcb-88ac-47d7843d724b': 423,
 '398e6759-bb37-46ac-9757-71bbd4acb7fe': 424,
 'f238bd6a-148c-4569-b103-1eb0ce14a99d': 425,
 '1af62486-8e4a-4418-8030-940e2747efaf': 426,
 '178ea505-bba2-40b8-a35a-47cad1cc40e8': 427,
 '4cacf9b9-6cc8-4397-91e0-4febf3d57b8f': 428,
 'c865f8de-9b19-416a-8999-ac61a9c14391': 429,
 'e9867ab8-8144-452e-a450-7c19f96c662c': 430,
 '088d7563-f696-48c6-be48-ba37e3da1045': 431,
 '91c42035-2dd6-4a4c-ac04-2fceed234f0e': 432,
 '547d2570-454b-4023-ada1-579ac3b30d51': 433,
 'b3b83613-e9be-4ddf-9739-7947bea8a757': 434,
 '042235cf-a3cd-4a0a-a8e9-81d5efeac9dd': 435,
 'd46f54d3-5f3b-49e7-8ce9-4109418448a2': 436,
 '3d2f716c-8e57-493d-8019-7bf3bb320676': 437,
 'bca15d91-02c2-421e-9095-890f2d303c40': 438,
 'bc50d593-0945-4971-90c1-2e5949bfcd22': 439,
 '2cfaf8a7-486f-4c71-a51c-9d0e51ad044c': 447,
 '0c202e22-3d3d-43f7-a5fd-0131fb368f86': 441,
 '8a455af8-9ae0-4199-96ef-be107a30ce6a': 442,
 '915eac38-d75b-48f5-a8f4-66879d601e50': 443,
 '7fcb872c-4fb0-4b60-ba8b-c37afcd33229': 444,
 'a265ce41-30dc-49ef-87c5-bce406e55799': 445,
 '07a0c457-0041-4c5c-a20c-49d927c61f4d': 446,
 'b99aacff-fc41-4f2d-96ec-0227e398b37f': 448,
 'faa89385-9bdd-4039-a009-b6371be6abf6': 449,
 '30da723e-8706-4630-b3b6-7458867b4bcd': 450,
 '83ef0b66-05ba-47a8-9790-5ac304bc3364': 451,
 'e165fe96-9b58-4eb1-9fad-c892bf14bd4a': 452,
 '9124b3e8-a969-4595-8056-d958bef8f2e5': 453,
 '6fd6069d-f9e5-402e-8360-52a586207168': 454,
 '1d959173-4cbc-4c2e-aa84-32f967a737a2': 455,
 'b2c1f97f-1dc7-44ca-9533-09c1eccbb798': 456,
 'eef3e5c6-e6d5-447d-a274-2132c9a55c68': 457,
 '5e911f87-7677-d938-d220-9968308e5c9e': 458,
 'b204be8b-f92d-4010-8eec-6c0b635d555d': 459,
 '087cb26e-96d2-4541-a4d7-1dfb303c053e': 460,
 '60ff08fa-6f73-49e5-af0a-e0eb6282e516': 461,

In [14]:
idx = id['d873346c-be5c-4208-8663-d66006d8983b']
sim_scores = [(i, c) for i, c in enumerate(cosine_matrix[idx]) if i != idx] # 자기 자신을 제외한 유저들의 유사도 및 인덱스를 추출 
sim_scores = sorted(sim_scores, key = lambda x: x[1], reverse=True) # 유사도가 높은 순서대로 정렬 
sim_scores[0:5] # 상위 5개의 인덱스와 유사도를 추출

[(19530, 0.19333999230186524),
 (19531, 0.19333999230186524),
 (12960, 0.1889467210201055),
 (3196, 0.18810067021720445),
 (25904, 0.18759032378720253)]

In [15]:
appli_once.iloc[[1073]]

,category_code,brand,price,user_session,subcategory
1073,appliances.kitchen.refrigerators,NaN,210.07,d873346c-be5c-4208-8663-d66006d8983b,refrigerators

In [16]:
appli_once.iloc[[19530]]

,category_code,brand,price,user_session,subcategory
19530,appliances.environment.vacuum,samsung,69.47,37e5d81c-3adc-4a38-8663-0115c212dca3,vacuum

In [17]:
appli_once.iloc[[19531]]

,category_code,brand,price,user_session,subcategory
19531,appliances.environment.vacuum,samsung,69.47,37e5d81c-3adc-4a38-8663-0115c212dca3,vacuum

In [18]:
appli_once.iloc[[12960]]

,category_code,brand,price,user_session,subcategory
12960,appliances.kitchen.kettle,redmond,28.01,64306efe-1112-40cd-be5c-d0b08030d4e0,kettle

In [19]:
appli_once.iloc[[3196]]

,category_code,brand,price,user_session,subcategory
3196,appliances.environment.air_heater,NaN,7.31,b90430b3-db02-4303-be5c-d1fb65207e9f,air_heater

In [20]:
appli_once.iloc[[25904]]

,category_code,brand,price,user_session,subcategory
25904,appliances.environment.vacuum,samsung,218.77,322b1c44-20bf-438b-8663-79219fbc43f6,vacuum

### electronics 제품간 추천
- segment2에 대한 추천

In [31]:
elec_once = RFM_without_view.loc[(RFM_without_view['Frequency'] < 2) & (RFM_without_view['event_type'] == 'purchase') & (RFM_without_view['main_category'] == 'electronics') & (RFM_without_view['RFM_label'] == 'segment2')]

In [32]:
elec_once.drop(columns=['event_type', 'main_category','Frequency','RFM_label'], inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [35]:
elec_once.drop(columns=['user_id','user_session', 'subcategory'], inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [37]:
elec_once.reset_index(drop=True, inplace=True)

In [38]:
elec_once.head()

   product_id           category_code  brand    price
0     1005104  electronics.smartphone  apple  1007.74
1     1005105  electronics.smartphone  apple  1397.09
2     1004258  electronics.smartphone  apple   731.47
3     1005129  electronics.smartphone  apple  1397.72
4     1003310  electronics.smartphone  apple   696.03

In [39]:
elec_once.shape

(7114, 4)

In [40]:
tfidf = TfidfVectorizer()

# Fit 후 dtm을 만듭니다.(문서, 단어마다 tf-idf 값을 계산합니다)
dtm_elec = tfidf.fit_transform(elec_once['category_code'])

In [41]:
cosine_matrix = cosine_similarity(dtm_elec, dtm_elec)

In [42]:
np.round(cosine_matrix, 4)

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [44]:
category = {}
for i, c in enumerate(elec_once['product_id']): 
  category[i] = c

category_id = {}
for i, c in category.items():
  category_id[c] = i

In [45]:
category_id

{1002101: 6177,
 1002524: 7019,
 1002525: 7049,
 1002528: 6808,
 1002531: 7006,
 1002532: 6978,
 1002535: 6317,
 1002536: 4509,
 1002540: 6915,
 1002544: 6941,
 1002545: 3213,
 1002547: 6015,
 1002548: 2763,
 1002628: 2857,
 1002629: 6628,
 1002633: 6824,
 1002634: 6333,
 1002796: 6740,
 1003028: 4818,
 1003153: 6184,
 1003281: 1459,
 1003304: 6181,
 1003305: 5684,
 1003306: 6987,
 1003307: 6072,
 1003308: 5185,
 1003309: 7080,
 1003310: 6911,
 1003311: 7061,
 1003312: 6875,
 1003313: 6993,
 1003314: 6847,
 1003315: 5109,
 1003316: 7041,
 1003317: 7087,
 1003318: 7066,
 1003319: 6600,
 1003363: 3772,
 1003523: 980,
 1003533: 4822,
 1003549: 4838,
 1003712: 6207,
 1003713: 4762,
 1003714: 946,
 1003751: 4028,
 1003768: 101,
 1003800: 6085,
 1003801: 4569,
 1003879: 4125,
 1003954: 5760,
 1003965: 2959,
 1003973: 4547,
 1004016: 2842,
 1004133: 1478,
 1004158: 6940,
 1004209: 5356,
 1004225: 7096,
 1004226: 6972,
 1004227: 7020,
 1004228: 6073,
 1004229: 6944,
 1004230: 6068,
 1004231: 129,
 1004232: 336,
 1004233: 385,
 1004234: 6872,
 1004235: 6024,
 1004237: 7073,
 1004238: 6575,
 1004240: 6696,
 1004241: 6054,
 1004242: 6191,
 1004243: 7100,
 1004244: 5971,
 1004246: 7004,
 1004247: 6939,
 1004249: 7094,
 1004250: 7113,
 1004251: 5945,
 1004252: 5293,
 1004253: 6845,
 1004254: 198,
 1004255: 6547,
 1004256: 6812,
 1004258: 7079,
 1004259: 6957,
 1004260: 1330,
 1004320: 4823,
 1004321: 4016,
 1004357: 3340,
 1004358: 6363,
 1004385: 2716,
 1004404: 4826,
 1004426: 1928,
 1004428: 6738,
 1004433: 471,
 1004434: 2861,
 1004441: 4541,
 1004449: 2236,
 1004461: 3733,
 1004505: 200,
 1004529: 3869,
 1004531: 4641,
 1004562: 815,
 1004565: 6854,
 1004566: 6496,
 1004617: 3917,
 1004650: 6725,
 1004653: 5708,
 1004655: 7081,
 1004657: 6602,
 1004659: 7106,
 1004661: 5210,
 1004662: 4497,
 1004665: 6802,
 1004666: 3807,
 1004670: 6537,
 1004671: 2127,
 1004708: 5019,
 1004720: 609,
 1004723: 2565,
 1004739: 534,
 1004740: 4715,
 1004741: 6050,
 1004750: 6810,
 1004751: 5649,
 1004766: 6561,
 1004767: 7051,
 1004768: 5542,
 1004781: 6827,
 1004785: 6064,
 1004788: 6395,
 1004792: 1710,
 1004793: 885,
 1004794: 5972,
 1004796: 4705,
 1004797: 6909,
 1004813: 3753,
 1004833: 6069,
 1004834: 3220,
 1004835: 5458,
 1004836: 6997,
 1004838: 6829,
 1004839: 3665,
 1004840: 6499,
 1004843: 6645,
 1004845: 6643,
 1004848: 6636,
 1004849: 6932,
 1004850: 2773,
 1004856: 6995,
 1004857: 4819,
 1004858: 5855,
 1004863: 5618,
 1004870: 7040,
 1004871: 1588,
 1004872: 4070,
 1004873: 6783,
 1004874: 5102,
 1004875: 5492,
 1004886: 1029,
 1004887: 530,
 1004888: 2669,
 1004897: 1521,
 1004901: 5645,
 1004903: 5151,
 1004905: 5035,
 1004910: 1341,
 1004916: 2640,
 1004917: 6594,
 1004920: 6256,
 1004929: 5020,
 1004934: 4524,
 1004944: 6586,
 1004945: 405,
 1004946: 6975,
 1004948: 5490,
 1004949: 7010,
 1004956: 1681,
 1004957: 6956,
 1004958: 5685,
 1004961: 5024,
 1004964: 2479,
 1004990: 536,
 1005002: 2806,
 1005003: 3746,
 1005004: 1877,
 1005006: 1936,
 1005007: 4478,
 1005014: 6942,
 1005015: 5946,
 1005016: 2833,
 1005017: 5042,
 1005021: 1102,
 1005022: 5778,
 1005032: 3922,
 1005050: 4937,
 1005064: 974,
 1005067: 7022,
 1005068: 5817,
 1005069: 3223,
 1005071: 7034,
 1005072: 6680,
 1005073: 7104,
 1005074: 7045,
 1005082: 443,
 1005083: 438,
 1005098: 5015,
 1005100: 5523,
 1005101: 3091,
 1005102: 7009,
 1005104: 6964,
 1005105: 7107,
 1005106: 7029,
 1005107: 6967,
 1005108: 6313,
 1005109: 6528,
 1005110: 5334,
 1005111: 6366,
 1005112: 7033,
 1005113: 6457,
 1005114: 5824,
 1005115: 7110,
 1005116: 7105,
 1005117: 6963,
 1005118: 6690,
 1005119: 7076,
 1005120: 6542,
 1005121: 6894,
 1005122: 6082,
 1005123: 6595,
 1005124: 6776,
 1005125: 5864,
 1005126: 6826,
 1005127: 6463,
 1005128: 4993,
 1005129: 7007,
 1005130: 6906,
 1005131: 5638,
 1005132: 7085,
 1005133: 6020,
 1005134: 4029,
 1005135: 7097,
 1005136: 7109,
 1005137: 6665,
 1005138: 7046,
 1005139: 7048,
 1005140: 6867,
 1005141: 7031,
 1005142: 5692,
 1005143: 6991,
 1005144: 7112,
 1005145: 6535,
 1005156: 633,
 1005157: 627,
 1005158: 4682,
 1005159: 4975,
 1005160: 4789,
 1005161: 4824,
 1005165: 3593,
 1005168: 5505,
 1005169: 3763,
 1005173: 7008,
 1005174: 7111,
 1005175: 6055,
 1005176: 3236,
 1005177: 6743,
 1005178: 6525,
 1005179: 5896,
 1005180: 4008,
 1005181: 6404,
 1005182: 6923,
 1005183: 6235,
 1005184: 5009,
 1005185: 5064,
 1005186: 7005,
 1005187: 5599,
 1005201: 4053,
 1005203: 5031,
 1005205: 6506,
 1005211: 6811,
 1005212: 2223,
 1005214: 1115,
 1005215: 6466,
 1005216: 6502,
 1005217: 3680,
 1005230: 6989,
 1005234: 4066,
 1005235: 2424,
 1005238: 5611,
 1005239: 6682,
 1005245: 6442,
 1005253: 6677,
 1005258: 1707,
 1005260: 5839,
 1005263: 5820,
 1201171: 462,
 1201285: 5022,
 1201286: 222,
 1201287: 492,
 1201289: 5030,
 1201297: 3555,
 1201379: 2849,
 1201383: 5073,
 1201388: 3270,
 1201389: 4174,
 1201391: 3660,
 1201397: 4827,
 1201432: 1533,
 1201448: 1343,
 1201453: 356,
 1201472: 1334,
 1201504: 2508,
 1201505: 532,
 1201513: 5850,
 1201574: 7101,
 1800579: 4676,
 1800930: 2768,
 1800931: 2700,
 1800944: 6687,
 1801427: 6299,
 1801513: 1394,
 1801539: 4361,
 1801544: 4192,
 1801546: 3964,
 1801548: 1612,
 1801551: 5827,
 1801555: 6881,
 1801563: 852,
 1801565: 441,
 1801579: 1623,
 1801623: 6229,
 1801631: 5198,
 1801658: 1071,
 1801690: 6162,
 1801691: 3891,
 1801699: 6412,
 1801701: 6378,
 1801704: 6041,
 1801710: 7017,
 1801712: 4899,
 1801739: 6302,
 1801748: 5390,
 1801761: 2286,
 1801762: 6954,
 1801766: 1846,
 1801784: 5900,
 1801785: 634,
 1801794: 1811,
 1801796: 4150,
 1801805: 5123,
 1801815: 3572,
 1801819: 386,
 1801820: 6739,
 1801824: 1482,
 1801829: 2574,
 1801849: 6817,
 1801853: 1194,
 1801854: 1246,
 1801860: 811,
 1801873: 6624,
 1801881: 6836,
 1801882: 4785,
 1801883: 926,
 1801896: 3109,
 1801897: 5203,
 1801899: 3923,
 1801901: 2371,
 1801905: 7047,
 1801908: 7054,
 1801909: 4604,
 1801910: 4739,
 1801911: 5319,
 1801912: 5308,
 1801913: 3872,
 1801915: 3566,
 1801917: 3130,
 1801918: 6868,
 1801922: 4966,
 1801929: 5952,
 1801934: 2147,
 1801938: 5311,
 1801940: 5823,
 1801951: 4748,
 1801953: 6986,
 1801955: 4042,
 1801960: 6770,
 1801963: 2681,
 1801964: 6164,
 1801971: 2005,
 1801975: 6310,
 1801990: 5810,
 1801995: 1661,
 1801997: 5726,
 1802005: 4711,
 1802008: 6905,
 1802009: 6030,
 1802010: 1208,
 1802012: 3682,
 1802014: 6262,
 1802019: 1405,
 1802024: 6022,
 1802026: 7065,
 1802037: 6848,
 1802043: 4948,
 1802047: 2369,
 1802063: 1181,
 1802067: 994,
 1802070: 2452,
 1802095: 3569,
 1802096: 6615,
 1802116: 2428,
 2300225: 2960,
 2300262: 4430,
 2300287: 7015,
 2300327: 1118,
 2300331: 3934,
 4802036: 5299,
 4802606: 1893,
 4803977: 4074,
 4804055: 6651,
 4804056: 7092,
 4804572: 7030,
 5100337: 5634,
 5100530: 494,
 5100562: 6113,
 5100563: 1555,
 5100565: 656,
 5100566: 5785,
 5100570: 4601,
 5100572: 5127,
 5100574: 1600,
 5100575: 1002,
 5100576: 2252,
 5100577: 2245,
 5100593: 2694,
 5100610: 5279,
 5100637: 4342,
 5100705: 3596,
 5100737: 2544,
 5100776: 2138,
 5100797: 7,
 5100852: 5156,
 5100854: 5160,
 5100855: 6919,
 5100856: 858,
 5100857: 1045,
 5100877: 3657,
 5100882: 6108,
 5100883: 2111,
 5100884: 112,
 5100889: 3677,
 5100891: 3563,
 5100899: 96,
 5801575: 202,
 5801656: 4787,
 8800093: 5751,
 8800399: 978,
 8800773: 826,
 9900158: 4745,
 9900411: 927,
 9900418: 130,
 9900420: 2260,
 11700260: 2829,
 14100052: 2011,
 14100459: 6292,
 14100460: 6297,
 14300064: 3474,
 14300093: 6720,
 18900021: 4875,
 18900167: 1566,
 18900183: 4530,
 18900455: 6853,
 21400532: 2283,
 21404234: 4360,
 21405199: 3164,
 21405370: 2703,
 21405875: 1758,
 21406273: 2704,
 21406799: 7071,
 21407004: 6931,
 21407014: 7067,
 21407206: 1638,
 21408847: 6689,
 21410400: 7068}

In [47]:
idx = category_id[21410400]
sim_scores = [(i, c) for i, c in enumerate(cosine_matrix[idx]) if i != idx] # 자기 자신을 제외한 유저들의 유사도 및 인덱스를 추출 
sim_scores = sorted(sim_scores, key = lambda x: x[1], reverse=True) # 유사도가 높은 순서대로 정렬 
sim_scores[0:5] # 상위 5개의 인덱스와 유사도를 추출

[(7, 1.0000000000000002),
 (31, 1.0000000000000002),
 (72, 1.0000000000000002),
 (96, 1.0000000000000002),
 (112, 1.0000000000000002)]

In [48]:
elec_once.iloc[[7068]]

      product_id       category_code   brand   price
7068    21410400  electronics.clocks  tissot  679.55

In [49]:
elec_once.iloc[[7]]

   product_id       category_code   brand    price
7     5100797  electronics.clocks  garmin  2393.88

In [50]:
elec_once.iloc[[31]]

    product_id       category_code  brand   price
31     5100856  electronics.clocks  apple  616.13

In [51]:
elec_once.iloc[[72]]

    product_id       category_code  brand   price
72     5100899  electronics.clocks  apple  643.26

In [52]:
elec_once.iloc[[96]]

    product_id       category_code  brand   price
96     5100899  electronics.clocks  apple  643.26

In [53]:
elec_once.iloc[[112]]

     product_id       category_code   brand    price
112     5100884  electronics.clocks  garmin  1248.66

### electronics 유저간 추천
- segment2 에 대한 추천

In [60]:
elec_user = RFM_without_view.loc[(RFM_without_view['Frequency'] < 2) & (RFM_without_view['event_type'] == 'purchase') & (RFM_without_view['main_category'] == 'electronics') & (RFM_without_view['RFM_label'] == 'segment2')]

In [61]:
elec_user.drop(columns=['product_id','event_type', 'main_category', 'subcategory', 'Frequency', 'RFM_label'], inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [62]:
elec_user.reset_index(drop=True, inplace=True)

In [63]:
elec_user.head()

,category_code,brand,price,user_id,user_session
0,electronics.smartphone,apple,1007.74,553492314,859d6cd6-a3d0-4049-8a0e-212a3d864d48
1,electronics.smartphone,apple,1397.09,551646372,bbef1e78-8279-41ac-8bd7-e459e1ad9f3e
2,electronics.smartphone,apple,731.47,553492314,859d6cd6-a3d0-4049-8a0e-212a3d864d48
3,electronics.smartphone,apple,1397.72,551646372,bbef1e78-8279-41ac-8bd7-e459e1ad9f3e
4,electronics.smartphone,apple,696.03,563963172,cf5993a5-17c9-41ef-a9c4-d1bfc624402a

In [64]:
elec_user.shape

(7114, 5)

In [65]:
tfidf = TfidfVectorizer()

# Fit 후 dtm을 만듭니다.(문서, 단어마다 tf-idf 값을 계산합니다)
dtm_elec_user = tfidf.fit_transform(elec_user['user_session'])

In [66]:
cosine_matrix = cosine_similarity(dtm_elec_user, dtm_elec_user)

In [67]:
np.round(cosine_matrix, 4)

array([[1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [68]:
user = {}
for i, c in enumerate(elec_user['user_id']): 
  user[i] = c

user_id = {}
for i, c in user.items():
  user_id[c] = i

In [69]:
user_id

{553492314: 2,
 551646372: 9,
 563963172: 4,
 547101682: 5,
 527225862: 6,
 563963947: 7,
 515414031: 8,
 534249929: 10,
 546373721: 11,
 556763735: 12,
 560361981: 13,
 514988855: 14,
 513465845: 15,
 516323877: 16,
 540817817: 17,
 521712163: 18,
 547308910: 19,
 562715444: 20,
 556310310: 21,
 563968655: 36,
 561582483: 27,
 563401481: 24,
 563970418: 25,
 563969332: 26,
 561962546: 28,
 563970672: 29,
 521203750: 30,
 542185768: 31,
 521843962: 32,
 540741354: 37,
 551624904: 35,
 553791455: 38,
 560436426: 39,
 552061422: 40,
 522554425: 41,
 563973738: 42,
 526750679: 43,
 542778634: 44,
 548144606: 76,
 519043940: 50,
 551322808: 47,
 521397658: 48,
 536589557: 49,
 517666246: 51,
 516251196: 52,
 562716401: 53,
 563976477: 54,
 513206475: 55,
 563979640: 56,
 563977910: 63,
 552311423: 58,
 551076980: 60,
 513286962: 61,
 517686800: 62,
 519877754: 64,
 536123941: 65,
 563981537: 66,
 563968953: 67,
 547787231: 70,
 520196501: 69,
 563978746: 71,
 559025270: 72,
 538518045: 73,
 514238663: 74,
 539565653: 75,
 551773558: 81,
 545836524: 78,
 527270075: 85,
 532543951: 80,
 542828755: 82,
 550850331: 84,
 517662623: 86,
 515375721: 87,
 513786184: 88,
 532317524: 89,
 563987968: 90,
 530476922: 91,
 513036476: 92,
 563988956: 93,
 517867863: 94,
 513836499: 95,
 515411457: 96,
 540220909: 97,
 516447280: 98,
 514348905: 99,
 543898094: 100,
 559870645: 101,
 526504303: 102,
 514791427: 103,
 563991830: 104,
 514098460: 107,
 563992376: 106,
 563992600: 108,
 549194821: 109,
 534209848: 110,
 546185573: 111,
 515595329: 112,
 550697550: 113,
 563563576: 118,
 514913057: 115,
 513694714: 116,
 515809372: 117,
 527833344: 119,
 514932164: 120,
 525382327: 121,
 554957317: 122,
 515440869: 123,
 563748835: 124,
 549872074: 125,
 563335922: 126,
 514276007: 127,
 560868667: 128,
 527915872: 129,
 518877982: 130,
 521409620: 131,
 514650798: 132,
 564000691: 137,
 518634960: 134,
 564001954: 135,
 530920433: 138,
 520565594: 139,
 563968125: 140,
 542719543: 141,
 520364359: 142,
 564002637: 143,
 513795453: 144,
 558504147: 145,
 550387926: 148,
 538758348: 147,
 534835264: 149,
 560674597: 150,
 513364575: 151,
 564007271: 152,
 514472723: 153,
 564007985: 154,
 564007558: 156,
 544396478: 157,
 516361164: 158,
 561236455: 159,
 538672491: 160,
 518302426: 161,
 524041164: 162,
 540759694: 163,
 516678918: 164,
 560831579: 165,
 518047085: 166,
 513352640: 167,
 515504462: 168,
 516263941: 169,
 554550887: 170,
 546677926: 171,
 518363364: 172,
 564007203: 173,
 558664320: 178,
 512832577: 175,
 545907746: 189,
 513862459: 177,
 521449285: 179,
 527856085: 181,
 521025518: 182,
 542218550: 183,
 548452091: 184,
 563995479: 186,
 558004473: 187,
 512373905: 188,
 561194982: 190,
 551702839: 193,
 517845324: 192,
 517399270: 194,
 533826065: 200,
 519257946: 196,
 547455239: 197,
 516495800: 198,
 563967196: 199,
 530216774: 203,
 531556202: 212,
 537689201: 204,
 512928414: 205,
 564020363: 207,
 533291553: 208,
 515945937: 210,
 548661134: 218,
 518358303: 213,
 539062573: 214,
 564023582: 215,
 515912831: 216,
 547567614: 217,
 513504028: 219,
 557962505: 220,
 520248949: 221,
 564011196: 222,
 513621488: 223,
 541263162: 224,
 564021253: 225,
 564025457: 235,
 523818791: 227,
 519370051: 228,
 563899695: 229,
 544680838: 231,
 527770822: 232,
 513536760: 233,
 516558830: 234,
 560765070: 238,
 515109676: 237,
 564026287: 240,
 515875020: 241,
 549569233: 242,
 515631886: 243,
 512918947: 244,
 563565065: 245,
 518632853: 246,
 555411723: 247,
 515574283: 248,
 517166933: 249,
 563778817: 250,
 564034292: 251,
 520206276: 252,
 554147016: 253,
 528288015: 254,
 545156032: 255,
 512506104: 256,
 527789583: 257,
 536189032: 258,
 546376165: 259,
 551064724: 272,
 564030193: 261,
 532931161: 273,
 559871588: 266,
 517313758: 270,
 515811062: 275,
 512931468: 279,
 535397368: 277,
 530669246: 278,
 543258895: 280,
 547338263: 283,
 529845175: 282,
 525021774: 284,
 540987074: 285,
 540073520: 286,
 544019336: 290,
 534460660: 288,
 531073872: 289,
 564045348: 297,
 512902121: 292,
 515184850: 293,
 514647722: 294,
 564044960: 303,
 543110738: 296,
 564042263: 298,
 562257467: 299,
 564047290: 301,
 564042802: 308,
 529204454: 305,
 545319448: 306,
 564049528: 307,
 546300856: 313,
 545575922: 310,
 564051290: 316,
 556052408: 314,
 536462741: 315,
 560328739: 317,
 564053235: 318,
 545351687: 328,
 539592131: 320,
 564052540: 325,
 535389630: 324,
 550918173: 326,
 563027781: 327,
 540777833: 329,
 534316917: 330,
 515426685: 331,
 564055147: 332,
 559462945: 338,
 559718765: 351,
 564058750: 335,
 513500667: 343,
 553007747: 337,
 564059986: 339,
 543168979: 340,
 517627698: 341,
 545510505: 342,
 546253152: 344,
 515842578: 345,
 517140264: 354,
 534243948: 347,
 536298198: 348,
 564060606: 349,
 514743328: 350,
 564060512: 352,
 532385883: 353,
 513436938: 355,
 536589837: 356,
 553057301: 357,
 517452866: 358,
 534441750: 359,
 517428412: 360,
 514923012: 361,
 543961615: 364,
 539454045: 365,
 564066795: 372,
 561270261: 367,
 512372698: 368,
 556438003: 369,
 563887983: 371,
 515978618: 373,
 548105641: 374,
 564068377: 375,
 564068715: 376,
 518767969: 377,
 516239293: 378,
 533374754: 379,
 564056753: 380,
 562193061: 386,
 516301518: 383,
 512707246: 387,
 543282311: 394,
 556391162: 388,
 563828477: 389,
 536387850: 390,
 542243295: 391,
 516717062: 393,
 519319428: 395,
 513276223: 396,
 561599383: 397,
 515523340: 398,
 526937723: 399,
 550236287: 400,
 564076569: 405,
 515315853: 402,
 546322060: 403,
 547894583: 404,
 522825299: 406,
 514935551: 407,
 552936030: 408,
 564073313: 411,
 512783141: 410,
 517115757: 415,
 564078382: 413,
 512377540: 414,
 527674590: 416,
 563247712: 417,
 543390659: 419,
 564082644: 420,
 516134014: 421,
 516252863: 422,
 564074560: 423,
 560101542: 424,
 562955047: 425,
 513190445: 426,
 512870907: 427,
 564087492: 432,
 535210734: 429,
 564088601: 430,
 527525722: 431,
 552720266: 433,
 514662207: 434,
 521539592: 435,
 518453105: 436,
 545035319: 437,
 513197700: 446,
 547205399: 439,
 544568403: 440,
 515868815: 441,
 541520592: 442,
 519319903: 444,
 543123426: 445,
 563368588: 447,
 518795794: 448,
 551821261: 449,
 545128489: 450,
 539395583: 451,
 536837441: 452,
 563646447: 453,
 539057612: 454,
 514315339: 455,
 529890347: 456,
 564082738: 460,
 522444157: 458,
 513508410: 463,
 564085620: 461,
 564078507: 462,
 517108118: 464,
 514292668: 465,
 532274576: 466,
 552269073: 471,
 527544233: 469,
 564098147: 474,
 534456110: 473,
 557014358: 475,
 532797376: 476,
 526174099: 477,
 518431944: 478,
 564102626: 479,
 513310258: 480,
 560167672: 481,
 513549251: 482,
 523166411: 483,
 522420222: 484,
 539799730: 485,
 562101631: 486,
 560103194: 487,
 542716738: 488,
 513651437: 489,
 564108581: 490,
 564038489: 493,
 560296699: 492,
 563313045: 494,
 516419753: 495,
 519162977: 502,
 530504504: 497,
 559482687: 498,
 564110414: 499,
 524505165: 500,
 558128231: 501,
 562442971: 511,
 517624172: 504,
 517473945: 505,
 524785701: 506,
 518361256: 515,
 515174967: 509,
 524161592: 510,
 514595739: 536,
 555180608: 514,
 515492009: 516,
 555617065: 532,
 552328780: 519,
 520197635: 520,
 564119056: 521,
 539717639: 534,
 513860117: 523,
 513642027: 524,
 525530844: 525,
 558801124: 535,
 564044899: 528,
 512749838: 529,
 564121232: 537,
 531698801: 542,
 527712660: 540,
 564122827: 539,
 564122892: 541,
 514918007: 543,
 515891087: 544,
 564127403: 552,
 512480682: 547,
 524054226: 549,
 564127021: 571,
 514172750: 551,
 541309703: 553,
 544421212: 556,
 558266328: 558,
 527758736: 559,
 518708729: 560,
 564130855: 561,
 564092038: 562,
 514371201: 569,
 558590555: 564,
 562591162: 566,
 561641218: 567,
 552982303: 570,
 531056723: 574,
 525252377: 573,
 513463450: 575,
 564134621: 576,
 512880068: 577,
 563943685: 578,
 514653301: 579,
 522770670: 586,
 530782508: 581,
 547670844: 582,
 563922242: 583,
 558321709: 584,
 541487392: 589,
 521202599: 587,
 529345515: 591,
 550808977: 590,
 519462145: 594,
 549754946: 593,
 515974362: 595,
 548561637: 596,
 535090853: 597,
 564142065: 598,
 535717586: 599,
 564144518: 600,
 531414502: 601,
 512489226: 602,
 513911785: 603,
 496432902: 604,
 548888766: 605,
 554580705: 606,
 564148281: 620,
 524148869: 608,
 549633910: 609,
 530883942: 616,
 516050785: 612,
 544253254: 614,
 532481942: 615,
 551404790: 617,
 541083969: 622,
 523920948: 623,
 554116310: 624,
 556197661: 634,
 508593823: 629,
 538849167: 633,
 564158362: 628,
 564159863: 632,
 564161487: 635,
 564161934: 636,
 560614079: 637,
 564167260: 638,
 514864074: 639,
 547327495: 640,
 562187489: 641,
 514545475: 642,
 540995836: 643,
 514816863: 644,
 537746280: 645,
 544874568: 646,
 554828426: 651,
 538328150: 648,
 550483369: 649,
 564178053: 652,
 516469585: 656,
 515999921: 657,
 522128766: 658,
 537267792: 659,
 515497863: 660,
 563941279: 661,
 517054028: 662,
 563691787: 663,
 530440053: 664,
 514072355: 665,
 514880078: 666,
 517938748: 667,
 517101276: 672,
 564201209: 674,
 561669255: 675,
 564203183: 676,
 514303450: 677,
 564205400: 678,
 552544799: 679,
 559419574: 681,
 512494982: 683,
 564210698: 684,
 538936015: 685,
 515042292: 686,
 513049048: 687,
 564221268: 688,
 540962641: 689,
 523761981: 690,
 517321115: 695,
 563980624: 692,
 563487311: 693,
 513389081: 694,
 515570416: 696,
 519979519: 697,
 513939687: 698,
 513667565: 699,
 519793688: 700,
 532009607: 701,
 515761366: 702,
 564234889: 703,
 515631104: 704,
 521231706: 705,
 514514191: 706,
 562626062: 709,
 512943342: 708,
 528055403: 710,
 538986938: 711,
 530512535: 712,
 547633172: 714,
 552255288: 717,
 564239424: 716,
 517405295: 718,
 556615860: 720,
 512888314: 721,
 526585122: 722,
 564243753: 723,
 529837958: 724,
 564241391: 725,
 564244473: 726,
 526155417: 727,
 533668371: 734,
 515637030: 729,
 514664658: 730,
 548808082: 731,
 561677421: 733,
 564246176: 735,
 552176425: 739,
 539455572: 737,
 535445314: 772,
 518922288: 740,
 512496255: 741,
 519243376: 742,
 545081991: 762,
 564249050: 745,
 564112697: 746,
 535727393: 748,
 564249529: 757,
 512438602: 750,
 559400369: 752,
 518673377: 779,
 531535068: 754,
 559999914: 755,
 524222296: 756,
 512421160: 758,
 564251263: 759,
 564250713: 760,
 517222022: 763,
 515407708: 764,
 553116689: 768,
 564249843: 766,
 564250806: 767,
 564250868: 777,
 564251907: 770,
 515796611: 776,
 564250273: 780,
 520111028: 781,
 524144634: 782,
 557455434: 794,
 559804831: 784,
 564253692: 785,
 514917814: 786,
 527757382: 788,
 515107043: 789,
 529049913: 798,
 551130262: 791,
 554328954: 792,
 564254964: 815,
 520474853: 799,
 541160249: 800,
 530195245: 804,
 524009669: 803,
 513202290: 805,
 515940710: 806,
 540017363: 807,
 545841163: 808,
 512883708: 809,
 564256659: 1030,
 513224935: 813,
 542707969: 814,
 551493909: 816,
 553337585: 823,
 540870541: 834,
 551466094: 819,
 564258380: 820,
 514651989: 824,
 543021639: 825,
 522331827: 827,
 564180844: 836,
 564093239: 837,
 552432129: 830,
 526235988: 832,
 564255670: 841,
 564247250: 835,
 541023235: 838,
 564262014: 839,
 522254104: 840,
 559810940: 842,
 516494870: 843,
 564262224: 845,
 514406195: 846,
 515003919: 847,
 518484600: 848,
 530611772: 852,
 561058463: 850,
 514747381: 856,
 564264267: 853,
 533758604: 855,
 557760586: 857,
 549651046: 858,
 519184922: 859,
 549744982: 860,
 517599941: 861,
 516895949: 862,
 548548364: 863,
 535326073: 864,
 513678750: 865,
 521487510: 866,
 513795404: 867,
 551758728: 868,
 525561417: 869,
 514940433: 870,
 515500604: 871,
 514708409: 872,
 523947175: 873,
 556281886: 874,
 513730071: 875,
 525345959: 876,
 550712708: 877,
 562713927: 878,
 513106409: 879,
 527895117: 880,
 563967983: 881,
 544303419: 882,
 564275543: 885,
 513390568: 884,
 564276722: 886,
 564113783: 887,
 542231541: 888,
 557748771: 895,
 520678076: 890,
 563709339: 891,
 523176136: 892,
 512597582: 893,
 533912719: 900,
 564280413: 903,
 513473110: 898,
 561840460: 899,
 519860746: 901,
 541776933: 902,
 564280987: 904,
 564281356: 905,
 515936407: 906,
 518437393: 907,
 538413771: 908,
 564283642: 913,
 563980482: 910,
 564283748: 927,
 550330450: 912,
 564283951: 914,
 552193261: 915,
 514082779: 917,
 512553949: 918,
 539602518: 920,
 513201777: 921,
 562807658: 922,
 556714464: 923,
 553648308: 924,
 564286849: 929,
 564283206: 928,
 526663039: 930,
 542657804: 931,
 564286368: 932,
 564287107: 933,
 517009786: 934,
 515871394: 935,
 554530549: 936,
 564286769: 937,
 513618636: 938,
 549225347: 939,
 564289859: 943,
 524837591: 941,
 562431155: 951,
 541059543: 952,
 544451499: 945,
 522180255: 946,
 555928147: 948,
 548563471: 949,
 550469943: 950,
 537543131: 953,
 529903356: 954,
 528376331: 955,
 512469937: 956,
 513639922: 957,
 564294149: 958,
 517992287: 959,
 522133339: 960,
 514022056: 961,
 564288541: 980,
 560852270: 963,
 530039254: 964,
 540466897: 978,
 523378460: 967,
 516680147: 968,
 532746608: 969,
 564296730: 989,
 515556931: 981,
 564297042: 979,
 564296308: 976,
 523189330: 977,
 561600225: 990,
 559022988: 988,
 548530215: 985,
 564297730: 993,
 553211155: 996,
 517171897: 992,
 516272103: 994,
 512743678: 995,
 544080830: 997,
 564297060: 998,
 551099341: 999,
 513712520: 1000,
 564269065: 1005,
 532379800: 1045,
 512882355: 1004,
 526010607: 1006,
 513446308: 1007,
 514233853: 1008,
 484811215: 1009,
 516542093: 1010,
 546153837: 1011,
 530176285: 1012,
 544998505: 1013,
 518504725: 1014,
 556997689: 1015,
 564251592: 1020,
 553224545: 1017,
 532608761: 1018,
 528405061: 1019,
 514766525: 1021,
 512895238: 1022,
 564305410: 1023,
 541996997: 1024,
 561570213: 1025,
 536596201: 1029,
 541483222: 1027,
 538168072: 1028,
 547001421: 1031,
 512487648: 1034,
 535219221: 1038,
 559810840: 1035,
 523477332: 1036,
 564290510: 1037,
 563605027: 1039,
 520306581: 1047,
 517008103: 1041,
 546839872: 1042,
 548585424: 1043,
 543303899: 1044,
 564309509: 1048,
 515349797: 1049,
 554876509: 1050,
 518881844: 1051,
 515038373: 1052,
 538392973: 1053,
 520655595: 1054,
 523974116: 1055,
 528425485: 1078,
 548728336: 1057,
 523959315: 1058,
 536038118: 1059,
 519037445: 1064,
 564294121: 1061,
 564312848: 1062,
 564313567: 1065,
 519018007: 1069,
 560726790: 1068,
 521356753: 1070,
 517019492: 1071,
 564315120: 1073,
 558338832: 1074,
 522728612: 1075,
 530512012: 1076,
 514285074: 1077,
 560511712: 1079,
 519992286: 1080,
 543142594: 1084,
 539145359: 1086,
 524349159: 1083,
 513764014: 1085,
 520249088: 1087,
 564318326: 1094,
 564315558: 1089,
 564317449: 1090,
 516483892: 1095,
 518122128: 1093,
 524683730: 1124,
 564318367: 1097,
 557260076: 1114,
 525211455: 1105,
 522634445: 1116,
 526765818: 1113,
 552803009: 1108,
 553313832: 1111,
 564317433: 1115,
 521511711: 1110,
 564320446: 1112,
 561839308: 1117,
 513860154: 1118,
 563744274: 1119,
 562574613: 1120,
 515093071: 1121,
 547833857: 1122,
 520194049: 1125,
 518906652: 1126,
 552948946: 1127,
 564326416: 1133,
 526610388: 1129,
 541436186: 1130,
 514738155: 1131,
 513518441: 1132,
 517605340: 1134,
 512640647: 1142,
 541793687: 1136,
 543412740: 1137,
 538197831: 1138,
 515677238: 1139,
 519230598: 1140,
 515516824: 1141,
 564330844: 1143,
 559410530: 1144,
 553751814: 1153,
 550369852: 1146,
 541306319: 1147,
 519088462: 1151,
 518887042: 1149,
 513147722: 1150,
 545332519: 1152,
 517157205: 1154,
 561448484: 1159,
 564333292: 1156,
 563226326: 1157,
 560632645: 1160,
 527938145: 1161,
 516280951: 1162,
 512839770: 1163,
 512754568: 1164,
 558931368: 1169,
 540281654: 1166,
 515479404: 1167,
 563067020: 1170,
 564335745: 1171,
 517265205: 1172,
 564336127: 1173,
 564336949: 1174,
 549806366: 1175,
 551153851: 1176,
 550696980: 1177,
 530968601: 1178,
 544677501: 1179,
 519058382: 1180,
 564338081: 1181,
 512423715: 1182,
 524885955: 1183,
 519321120: 1184,
 547625645: 1185,
 516436842: 1186,
 564340237: 1192,
 524207470: 1188,
 564323745: 1190,
 548842998: 1191,
 564340579: 1199,
 537432050: 1194,
 513784398: 1195,
 564341326: 1197,
 523411897: 1198,
 519594447: 1215,
 518136284: 1201,
 564343531: 1202,
 564338965: 1203,
 564341746: 1204,
 564340840: 1205,
 563699932: 1223,
 531505934: 1207,
 564164867: 1209,
 535787376: 1210,
 515971306: 1218,
 545661149: 1219,
 512717053: 1213,
 514158334: 1261,
 564346018: 1222,
 530925181: 1225,
 544630661: 1221,
 564345866: 1224,
 514163515: 1226,
 516525720: 1227,
 513528489: 1228,
 552877700: 1229,
 545020022: 1230,
 515520680: 1231,
 564339748: 1254,
 549135913: 1234,
 564348676: 1241,
 531943849: 1237,
 514231204: 1238,
 536000950: 1239,
 513130812: 1243,
 515395768: 1244,
 540284601: 1245,
 526617627: 1246,
 522496351: 1247,
 546838194: 1248,
 564349198: 1249,
 564346880: 1264,
 520553052: 1251,
 564350466: 1252,
 518614436: 1262,
 512471773: 1255,
 512723162: 1256,
 512700467: 1257,
 513643635: 1258,
 514909318: 1260,
 547573647: 1263,
 512713226: 1286,
 522064739: 1266,
 518638907: 1267,
 544273616: 1268,
 516432844: 1269,
 514894732: 1270,
 560270180: 1271,
 564358735: 1272,
 561227196: 1273,
 564358310: 1274,
 549539986: 1275,
 558708652: 1276,
 530821118: 1277,
 528101810: 1278,
 523153918: 1279,
 536921730: 1280,
 560007793: 1283,
 ...}

In [71]:
idx = user_id[565966895]
sim_scores = [(i, c) for i, c in enumerate(cosine_matrix[idx]) if i != idx] # 자기 자신을 제외한 유저들의 유사도 및 인덱스를 추출 
sim_scores = sorted(sim_scores, key = lambda x: x[1], reverse=True) # 유사도가 높은 순서대로 정렬 
sim_scores[0:5] # 상위 5개의 인덱스와 유사도를 추출

[(7067, 1.0000000000000002),
 (7068, 1.0000000000000002),
 (4306, 0.18505806770304392),
 (2757, 0.17569227655160585),
 (1367, 0.17409519720961947)]

In [73]:
elec_user.loc[elec_user['user_id'] == 565966895]

,category_code,brand,price,user_id,user_session
7067,electronics.clocks,tissot,1050.22,565966895,b3a7e0f4-26a4-42e1-af6c-6ad9ab87636c
7068,electronics.clocks,tissot,679.55,565966895,b3a7e0f4-26a4-42e1-af6c-6ad9ab87636c
7071,electronics.clocks,tissot,741.33,565966895,b3a7e0f4-26a4-42e1-af6c-6ad9ab87636c

In [74]:
elec_user.iloc[[4306]]

,category_code,brand,price,user_id,user_session
4306,electronics.smartphone,samsung,771.94,544053861,20da16b2-26a4-46d8-b608-fb35c0d8575e

In [75]:
elec_user.iloc[[2757]]

,category_code,brand,price,user_id,user_session
2757,electronics.smartphone,apple,1692.81,564816718,f2f95827-42e1-431e-9172-63d10b4e6648

In [76]:
elec_user.iloc[[1367]]

,category_code,brand,price,user_id,user_session
1367,electronics.smartphone,apple,1043.97,512951857,ce1e3b01-1a34-42e1-9eff-4c76a72c7cac